### ISSUE TITLE
MouseEvent.which in Firefox

### ISSUE THREAD

**Issue by bassu** [marijnh/Eloquent-JavaScript#154]
In [mouse motion](http://eloquentjavascript.net/14_event.html#p_Z1h4BQYT0/) at line 16, `event.which` is always *1* in Firefox (at least on OSX and Linux, as that's what I have tested in), so the mouse release is not detected.

However using `MouseEvent.buttons` works! Not sure if this is a browser bug but I'm leaving a note here anyway as I noticed Marijn on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent.which) thinking *the-powers-that-be* may know better :smile:

**Comment by marijnh** [comment]
Oh, that's pretty bad. I've fixed it in the online version in the attached patch. Note that `buttons` does not work on Webkit-based browsers, so we have to check both.

**Comment by bassu** [comment]
@marijnh Thanks for the quick fix :beers:
