### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by hectorip** [marijnh/Eloquent-JavaScript#157]
Hello Martin! Would you mind if I try to translate your awesome work to Spanish? My uncle wants to learn coding and I think this one of the best books to introduce him to programming, but he doesn't understand english. It would be also helpful for people beginning in coding that doesn't understand very well english or prefer to learn in his mother tongue. Thanks in advance!

**Comment by hjoaco** [comment]
Si Marijnh lo aprueba te doy una mano! :)

**Comment by marijnh** [comment]
Muy bien! Please read [this](https://github.com/marijnh/Eloquent-JavaScript/wiki/Translation) document first, and come back with any questions you have.

**Comment by hectorip** [comment]
Ready @marijnh, ¡Listo @hjoaco a darle!

**Comment by marijnh** [comment]
Great. Make sure you start from the _current_ state of the repository (your branch is, for some reason, pointing at an eight month old commit)
