### ISSUE TITLE
Comparing null and undefined in Chapter 5, page 100

### ISSUE THREAD

**Issue by nashmaniac** [marijnh/Eloquent-JavaScript#160]
On Page 100 the reduceAncestors function is : 

```javascript
function reduceAncestors(person, f, defaultValue) {
    function valueFor(person) {
        if(person == null) /* Line under consideration*/
            return defaultValue;
        else
            return f(person, valueFor(byName[person.mother]), valueFor(byName[person.father]);
    }
    return valueFor(person);
}
```

When no value for the supplied name is found in the byName object, the person variable holds a value of undefined.

Hence the comparison   ``` if(person == null)``` in such case, is equivalent to ``` if(undefined == null) ```
Which works as expected, but if comparison is done with the identity comparison operators the function fails because 
```
console.log(undefined == null);  // true
console.log(undefined === null);  //false
```

Why not directly compare person with undefined itself and switch 
``` if (person == null) ``` to ``` if(person == undefined)``` ?

**Comment by marijnh** [comment]
This is intentional. As described [here](http://eloquentjavascript.net/01_values.html#p_MzUL8LaoQ2) I am a strong proponent of using `== null` and treating null and undefined as interchangeable, so that you have one less thing to worry about.
