### ISSUE TITLE
Page 238 pdf

### ISSUE THREAD

**Issue by xgfd** [marijnh/Eloquent-JavaScript#161]
```
document.getElementById("quote").appendChild(
elt("footer", ---"",
elt("strong", "Karl Popper"),
```
should be
```
document.getElementById("quote").appendChild(
elt("footer", "---",
elt("strong", "Karl Popper"),
```
This issue doesn't exist in the source nor the online version.

**Comment by marijnh** [comment]
Indeed. Thanks for pointing that out. Must have happened during layout. I've added a note to the [errata page](http://eloquentjavascript.net/errata.html)
