### ISSUE TITLE
Long lines in code examples go over the edge of the page

### ISSUE THREAD

**Issue by looeee** [marijnh/Eloquent-JavaScript#174]
I'm using the epub downloaded from http://eloquentjavascript.net/

Long lines in the code example go over the edge of the page and cant be read. I'm using a Kobo Aura, but also tested this in Calibre Viewer. Changing font size or margins doesn't fix it.

**Comment by marijnh** [comment]
Is there a standard minimum page width for epub books? I don't have any device that consumes them, and Calibre's viewer seems to simply resize the pages to the window size. I've tried to keep code lines short, and give them a modest font size, but I'm not sure how to solve this (or what the constraints even are).

**Comment by marijnh** [comment]
I've added a media query to make the code font smaller for small screens, which seems to help some. If someone has a better idea feel free to comment.
