### ISSUE TITLE
Chapter 5 - counting ancestors 

### ISSUE THREAD

**Issue by OneHwang** [marijnh/Eloquent-JavaScript#176]
I believe Emile Haverbeke had 7 ancestors who lived to age 70 and had 31 ancestors in the records. However, I believe that in your calculations, you found 8 long-living people and 55 ancestors because 1) you may be counting Emile Haverbeke as an ancestor to himself and 2) if a person is the parent of multiple ancestors, you may be counting them multiple times. If you intend to use these counting conventions, it would be helpful if you state them in the book. Thank you.

**Comment by marijnh** [comment]
Thanks for reporting this. I've fixed the function to not count the initial argument, and added a note to the text to explain what kind of count it is supposed to be doing. See 23cf0495a7df463e2ab23c2d5666707bebb72f04
