### ISSUE TITLE
Chapter 04 question

### ISSUE THREAD

**Issue by joaostein** [marijnh/Eloquent-JavaScript#177]
Hey,

On Chapter 4, on the section **"String and their properties"** the first paragraph:

> _"We can read properties like `length` and `toUpperCase` from string values. But if you try to add a new property, it doesn’t stick."_

The statement says that the `toUpperCase` is a property, is it accurate?  Shouldn't it be a method?

**Comment by marijnh** [comment]
JavaScript methods are just properties that happen to hold functions.

**Comment by joaostein** [comment]
thanks thanks :)
