### ISSUE TITLE
Catching http request errors in Node.js 

### ISSUE THREAD

**Issue by OneHwang** [marijnh/Eloquent-JavaScript#185]
The solution to the content negotiation problem suggests http request errors can be caught through the following:
 
`
    readStreamAsString(response, function(error, content) {
      if (error) throw error;
`
However, if the bogus "application/rainbows+unicorns" is included as a data type in the request to eloquentjavascript.net/author, Node.js does NOT throw an error. Instead, it appears to treat the response from the server like regular content, and prints the following:

`
<html>
<head><title>406 Not Acceptable</title></head>
<body bgcolor="white">
<center><h1>406 Not Acceptable</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
`

It would be useful if 1) you could explain why browser consoles recognize this error, but Node.js does not and 2)  you could provide a solution that would catch this error in Node.js.

Thanks.

**Comment by marijnh** [comment]
You can check the response status code in your request callback by looking at the `statusCode` property of the response object. Attached patch adds this to the solution.
