### ISSUE TITLE
Make sandbox more secure

### ISSUE THREAD

**Issue by rafis** [marijnh/Eloquent-JavaScript#188]
It is easy to bypass sandbox using `parent` like:

    parent.document.body.style.backgroundColor = "red";

I have not tried with TamperMonkey, but I think this will work:

    setupEnv: function() {
      ...
      win.parent = win;
      ...
    }

Another protection `<iframe src="empty.html" style="display: none;" sandbox="allow-scripts">` - also haven't tried.

http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/
http://www.html5rocks.com/static/demos/evalbox/index.html

**Comment by marijnh** [comment]
What would be the benefit of this, though? Prevent people from hacking their own view of the book?

**Comment by rafis** [comment]
No, they will admire your sandbox "Wow, Contextify in a browser!", like I did, and perhaps will ask you to extract to independent project.

**Comment by marijnh** [comment]
Ah, in that case, I think the right way to go is to fork it and publish your own modular, secure, and possibly even documented version. Security is simply not an issue for my use case, so I don't want to put effort into it.
