### ISSUE TITLE
HELP ME!!! Version Spanish

### ISSUE THREAD

**Issue by eliezerpujols** [marijnh/Eloquent-JavaScript#196]
Please, I'm desperate, make a version in Spanish... Pleaseeeeee!!! :+1:

**Comment by hectorip** [comment]
We have a partial version in:

  

https://github.com/hectorip/Eloquent-JavaScript-es  

  

we are working on it, and the HTML version is being published in:

  

http://hectorip.github.io/Eloquent-JavaScript-ES-online/

**Comment by eliezerpujols** [comment]
@hectorip (In Spanish), el problema recide en que estan dando pasos lentos, y deberas quiero aprender javascript. No los culpo es un proyecto OpenSouce, pero por lo menos tenga en cuenta que hay personas deseosas de la traduccion. Gracias!

**Comment by marijnh** [comment]
This isn't something you can just demand. @hectorip pointed you at the relevant project. Closing this.
