### ISSUE TITLE
new legend[ch]() throws error Legend[char] is not a constructor

### ISSUE THREAD

**Issue by steelx** [marijnh/Eloquent-JavaScript#201]
at 07_elife file
Under: The world object

```
function elementFromChar(legend, ch) {
  if (ch == " ")
    return null;
  var element = new legend[ch]();
  element.originChar = ch;
  return element;
}
```
This line when initialized `var element = new legend[ch]();` throws error: `VM1303:137 Uncaught TypeError: legend[ch] is not a constructor`

Kindly revert.

**Comment by marijnh** [comment]
Could it be that you're feeding it a character that hasn't been defined in the given `legend` object?

**Comment by steelx** [comment]
@marijnh Im passing this `var world = new World(plan, {'#': Wall, 'o': BouncingCritter});`

**Comment by marijnh** [comment]
Are there characters in your plan that aren't `#` or `o`?

**Comment by steelx** [comment]
this is the variable im using.
```
	var plan =
 ["############################",
  "#      #    #      o      ##",
  "#                          #",
  "#          #####           #",
  "##         #   #    ##     #",
  "###           ##     #     #",
  "#           ###      #     #",
  "#   ####                   #",
  "#   ##       o             #",
  "# o  #         o       ### #",
  "#    #                     #",
  "############################"
];
```

**Comment by steelx** [comment]
I think I i typed something wrong, Im getting `undefined` for some `char`'s 
Sorry for this issue.
