### ISSUE TITLE
refactor require function

### ISSUE THREAD

**Issue by dongyuwei** [marijnh/Eloquent-JavaScript#202]
current require function  https://github.com/marijnh/Eloquent-JavaScript/blob/master/10_modules.txt#L465 may be better as this: 
```
function require(name) {
  if (name in require.cache)
    return require.cache[name];

  var code = new Function("exports, module, require", readFile(name));
  var exports = {}, module = {exports: exports};
  code(exports, module, require);

  require.cache[name] = module.exports;
  return module.exports;
}
require.cache = Object.create(null);
```
The key point is pass `require` as a third parameter to `code` function. Why?  Because it's usually the required source code may contains other `require()` functions. If we does not pass the `require` function, then the inner `require` call must referenced to a global `require` function. Conflict with the __global__  `require` is a bad idea. For example, we may need to run/test the bundled code in nodejs(which has a `require` in `global`). 

My project [tiny-asset-pipeline](https://github.com/dongyuwei/tiny-asset-pipeline/blob/master/lib/js/require.js) use the similar code. The bundled/packed code run in a anonymous function(see https://github.com/dongyuwei/tiny-asset-pipeline/blob/master/lib/js/combineOne.js#L62), so I passed the `require` function to `new Function`.

**Comment by marijnh** [comment]
Yes, that's how you'd do it in a [real system](https://github.com/marijnh/moduleserve/blob/master/client.js#L67). But for an example implementation, this doesn't get in the way of illustrating the concept.
