### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by sujinleeme** [marijnh/Eloquent-JavaScript#206]
Hi. @wengdiiiy and I'd like to translate this book in Korean language.
This is our working repository :  https://github.com/sujinleeme/Eloquent-JavaScript-ko

**Comment by marijnh** [comment]
Wonderful! Let me know if you run into any issues with my strange build system.

**Comment by sujinleeme** [comment]
@marijnh I found that this textbook was published last 2013 in Korea. I want to confirm it is possible to translate in Korean and release on the web. Korean version of this textbook is available through this [link](http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788960773868).

**Comment by marijnh** [comment]
Yes, you are free to create and distribute a not-for-profit translation.
