### ISSUE TITLE
An error in sandbox on http://eloquentjavascript.net/code/#17.2

### ISSUE THREAD

**Issue by IgorKonovalov** [marijnh/Eloquent-JavaScript#208]
There is a small error - without looking at the answers second line (function all) is 
`return new Promise(function(success, fail) {` but should be 
`return new Promise(function(succeed, fail) {` 
- as it is in answers section

**Comment by marijnh** [comment]
Why should it use that variable name?

**Comment by IgorKonovalov** [comment]
It's not a thing to be worried about at all - I was comparing exercise data sample and it's answer - name of variable is different and it was confusing for me at that time. It's my stupidity and nothing else - not being able to match variables names. Sorry for inconvenience, it's not a issue really. Thanks for the book, it's awesome!
