### ISSUE TITLE
A question about chapter 15  "A platform game"

### ISSUE THREAD

**Issue by TroyBug** [marijnh/Eloquent-JavaScript#212]
Hi,@marijnh,recently I have been reading the book,and running the code at [chapter 15](http://eloquentjavascript.net/code/#15.1),I found that when the player was falling down and close to the ground,it would move slowly and finally on the ground.It looks strange when the player jumping.
[detail here](https://i.stack.imgur.com/MWo93.gif)
I don't know how to fix it.Would you mind helping me?Thanks a lot.

**Comment by marijnh** [comment]
Yes, that's an effect of the way collision detection is implemented -- when an object would collide with another object, it is simply stopped. In this case, the player is stopped, and then slowly pulled down by gravity again. This was done intentionally, to keep the implementation simple. A more correct implementation could compute the exact point at which the objects would collide, and move them there before stopping them. That does require some non-trivial mathematics, so I consider it out scope for the book.
