### ISSUE TITLE
Better explanation chapter 10

### ISSUE THREAD

**Issue by maesitos** [marijnh/Eloquent-JavaScript#213]
**[chapter 10](http://eloquentjavascript.net/10_modules.html)** should explain the the important role the lexical scoping and/or the closure play in the _**define**_ function declaration. 

```
function define(depNames, moduleFunction) {
  var myMod = currentMod;
  var deps = depNames.map(getModule);

  deps.forEach(function(mod) {
    if (!mod.loaded)
      mod.onLoad.push(whenDepsLoaded);
  });

  function whenDepsLoaded() {
    if (!deps.every(function(m) { return m.loaded; }))
      return;

    var args = deps.map(function(m) { return m.exports; });
    var exports = moduleFunction.apply(null, args);
    if (myMod) {
      myMod.exports = exports;
      myMod.loaded = true;
      myMod.onLoad.forEach(function(f) { f(); });
    }
  }
  whenDepsLoaded();
}
```

When a dependency runs `myMod.onLoad.forEach(function(f) { f(); });` it actually runs the function "bind"—enclosed—to the "parent" module, that is, **_myMod_** points to the parent module.

This will not only help people understand the code but will go over closures again—repetition is how we learn don't we?

I wasn't familiarized with lexical scoping and it took me a while to see this.

**Comment by marijnh** [comment]
Lexical scoping is discussed in chapter 3, though, and readers are assumed to understand it by this point.

**Comment by Xiaohong-Deng** [comment]
here, is it possible that `whenDepsLoaded` for a specific module, say `mod1`, to be called more than once? say `deps.forEach` pushed `whenDepsLoaded` to `dep1`. by the time the call to `whenDepsLoaded` at the bottom, `dep1` has been loaded, meaning `whenDepsLoaded` for `mod1` has been called once. then `whenDepsLoaded` called by `mod1` itself will apply `moduleFunction` again. is that the case?
