### ISSUE TITLE
Mouseover/Mouseout hacks in Chapter 14 unnecessary/confusing

### ISSUE THREAD

**Issue by shoemakerdr** [marijnh/Eloquent-JavaScript#225]
I first want to say that your book is one of the best resources out there on learning Javascript, and it was the catalyst for getting me started with programming. Thank you so much for writing it and putting it out there for us to learn and grow from.

My issue pertains to a section about [potential problems with propagating 'mouseout' events](https://github.com/marijnh/Eloquent-JavaScript/blob/master/14_event.txt#L498).

You offer a hack that will check if the node that dispatched the event is a related node. However, this seems unnecessary, and (when I was first learning about these) it was very confusing. The workaround you made is unnecessary because although the parent node (the node with the event listener) is dispatching a mouseout event, the child that it is moving onto is dispatching a 'mouseover' event that bubbles up and clobbers the mouseout event of the parent. The [W3 spec] (https://www.w3.org/TR/DOM-Level-3-Events/#event-type-mouseover) goes over 'mouseover':

> A user agent MUST dispatch this event when a pointing device is moved onto the boundaries of an element. This event type is similar to mouseenter, but differs in that it bubbles, and that it MUST be dispatched when the pointer device moves onto the boundaries of an element whose ancestor element is the event target for the same event listener instance.

You can even check to see that, if you change the code in the sandbox to remove the event.relatedTarget hack, it still works.

**Comment by marijnh** [comment]
It's true that when the out- and over-effects directly cancel each other out, as they do in the example, you don't need that check. But there are many effects that don't have that property, or they are expensive to create (the example would set and reset the style for no reason if you cross the boundaries of the child node). So this is definitely something to know when working with mouseover-based event handlers. I'll try to make the example more representative of the problem in the next edition.

**Comment by shoemakerdr** [comment]
Got it. Thanks!
