### ISSUE TITLE
Fixing a leak - Security Issue

### ISSUE THREAD

**Issue by SimonAltrogge** [marijnh/Eloquent-JavaScript#226]
While solving the aforementioned exercise it has come to my attention that the RegExp given in your solution (even with the "global" flag enabled) does not catch the use of multiple double dots. As far as I understand, the replacement is not done before searching for further matches. Therefore one match will be found in "/../../" but after that only "../" is left to search and does not match the RegExp given in your solution. So in the end, when the replacement is done, we are still left with "/../".

I might be wrong about the technical side, but one way or another, the problem persists. I fixed it by using this RegExp instead: `/(\/|\\)(\.\.(\/|\\)?)+(\/|\\|$)/g`

I think this issue should be addressed as soon as possible. I used the server with the first fix included for the next exercise "A public space on the web" and even though I do have a firewall and a router it was accessible online and had this security problem. I managed to delete a file where it should not be possible.

Besides all that, i want to take the chance and thank you for the brilliant book you wrote in Eloquent JavaScript!

**Comment by marijnh** [comment]
Ugh, yeah, that's definitely broken. The problem is that the regular expression will _cover_ the second slash, and thus after replacing one instance, the continued search starts after that slash, and thus a second adjacent instance won't match.

Attached patch adds a loop that repeatedly does the replace from the start until the regexp no longer matches.

**Comment by SimonAltrogge** [comment]
Thank you very much for your response. Since you chose a different fix than the RegExp I suggested, I am wondering whether something is wrong about it. Is my RegExp still insecure or did you chose a different fix for different reasons?

**Comment by marijnh** [comment]
The regexp would also replace four dots in a row, and, being a rather big and complicated regexp, seems like it'd be harder for readers to understand than adding a loop.

**Comment by SimonAltrogge** [comment]
Oh, you are right about that one. I managed to fix it by just adding some braces and a quantifier to your original solution: `/((\/|\\)\.\.)+(\/|\\|$)/g`.

This is not a request to change it but just my ambition to solve it with a single RegExp. I will stop bothering you now, have a good day!
