### ISSUE TITLE
Ch.20, file server | GET method fails due to incompatibility with current version of mime package

### ISSUE THREAD

**Issue by zemccartney** [marijnh/Eloquent-JavaScript#228]
Hi there,

I'm currently working through chapter 20. In the file server explanation, I found that GET requests for existing files would fail with the following error: `TypeError: require(...).lookup is not a function`

This is because mime, in its current version (2.0.1), has changed `lookup` to `getType`

Seems like a total pain to keep the text in-sync with the packages you reference. Maybe a note on where to start debugging in case of such errors? I just did a text search in the Mime package's constructor and found the renamed function. 

Or, I realized only after figuring this out that I overlooked that you list the exact version installed at time of writing in your code example and that I could have just installed that version :) Sorry if that's the short answer here.

Anyways, thanks for the great book. For what it's worth, I've learned a ton, enjoyed reading and working through the examples every step of the way.

**Comment by marijnh** [comment]
Ah, I hadn't noticed that there was an incompatible 2.0. Yes, that's confusing. I've updated the `npm install` command to explicitly install 1.4.0 in attached patches. Will make sure to be more explicit about versions the next time I update the text.
