### ISSUE TITLE
weresquirrel: calculating a correlation returns NaN

### ISSUE THREAD

**Issue by kwiat1990** [marijnh/Eloquent-JavaScript#235]
I'm reading your book and I must admit that it's a great guide to programming. I've already played a little bit with the code from the book and I've found myself in a situation in which I have just a couple of entries in my Journal. Let's assume I have something like this:

```
addEntry(['work', 'TV', 'spaghetti', 'swimming pool'], false);
addEntry(['work', 'running', 'touched tree'], false);
addEntry(['work', 'weekend', 'peanuts', 'touched tree'], true);
addEntry(['work', 'weekend', 'peanuts'], true);
```
Then using` tableFor` function an `work`  as one of its parameters it returns an array of  `[0, 2, 0, 2]`, which by calculating Phi (using `phi` function) will throw a `NaN`.

**Comment by marijnh** [comment]
See my response in #97.
