### ISSUE TITLE
What Release date we can expect?

### ISSUE THREAD

**Issue by IamManchanda** [marijnh/Eloquent-JavaScript#236]
Hey @marijnh sir
To let you know I am eagerly awaiting for the book to be released :candy: 

What is the release month we can expect? :heart: :heart_eyes: 
January? February? :smiley:

**Comment by marijnh** [comment]
I'm not at a point where I can promise anything, but I'm aiming for January. That is the web version -- the paper version will take quite a bit longer.

**Comment by IamManchanda** [comment]
@marijnh sir: I am looking for web version only :smile:
A book can't give runnable editor after all :wink:  
Hope I learn a lot from you in 2018 that I remember it my whole life :smile:

**Comment by IamManchanda** [comment]
Hey @marijnh sir
Is that estimation/aim correct or we have to wait a bit more??

---

PS: Thanks for what you do!

**Comment by marijnh** [comment]
I'm pretty sure I'll be able to get a readable version online this month. You can start reading chapter 1 to 18 already at eloquentjavascript.net/3rd_edition/preview/ (the intro and the last chapters are still the old text).

**Comment by IamManchanda** [comment]
Superb Sir... Can't tell you how awesome it is :)
