### ISSUE TITLE
How to build the 3rd edition from source?

### ISSUE THREAD

**Issue by varmanishant** [marijnh/Eloquent-JavaScript#244]
I installed the dependencies like this:

`npm install acorn codemirror uglify-js markdown-it markdown-it-sub markdown-it-sup mold-template`

Still I get this error:

```
node src/chapter_info.js > html/js/chapter_info.js                                                                                                                       
File  11_1_family_tree.js  does not exist. { Error: ENOENT: no such file or directory, open 'code/solutions/11_1_family_tree.js
....
....
/home/nishant/packages/Eloquent-JavaScript/src/chapter_info.js:66
          solution: type == "html" ? prepareHTML(solution.trim(), includes) : solution.trim() 
TypeError: Cannot read property 'trim' of undefined
```

**Comment by marijnh** [comment]
Chapter 11 is in flux. You can just do `touch code/solutions/11_1_family_tree.js` to get past this error. I'll push a finished, working version in a few days.

**Comment by marijnh** [comment]
(It should build out of the box again. Chapter numbers and linking for chapters past 12 is still a mess.)

**Comment by varmanishant** [comment]
That works. I didn't check the number linking part. Please upload the new version as soon as possible :)
