### ISSUE TITLE
No support for custom string for 'beforeunload' event

### ISSUE THREAD

**Issue by Powell-v2** [marijnh/Eloquent-JavaScript#247]
Hi there,

I'd like to point out that custom text is being ignored in recent versions of all major browsers ([see compatibility table on MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload#Browser_compatibility)). Instead, generic warning is displayed.

https://github.com/marijnh/Eloquent-JavaScript/blob/8aae9b429cc5aed37086c97268afb3f9631f64be/14_event.txt#L693-L696

**Comment by marijnh** [comment]
I did not know that, thanks for the heads-up! Attached patch updates the description.

**Comment by Powell-v2** [comment]
Glad to help : )
