### ISSUE TITLE
Add tip on how to test touch events

### ISSUE THREAD

**Issue by Powell-v2** [marijnh/Eloquent-JavaScript#248]
Section "Touch events" ([3rd edition, chapter 15](http://eloquentjavascript.net/3rd_edition/15_event.html)) features an example which, in my opinion, deserves an extra line of explanation for those reading in desktop browser. Namely, I would mention _responsive design mode_  and its ability to emulate mobile devices.

**Comment by marijnh** [comment]
I don't want to go into specific features of single browsers in the book, and dev tools change so fast that it'd be out of date in half a year anyway, so this is intentionally not mentioned.

**Comment by Powell-v2** [comment]
Well, there is no need to go into details - plenty of docs available describing dev tools functionality. I thought it might help those new to web dev. Could be just one sentence : )
