### ISSUE TITLE
Blockquote before/after chars are messed up

### ISSUE THREAD

**Issue by krulik** [marijnh/Eloquent-JavaScript#251]
Encountered in [Chapter 5](http://eloquentjavascript.net/3rd_edition/05_higher_order.html):

![image](https://user-images.githubusercontent.com/1469785/35676052-fe938dec-0752-11e8-9666-af69c324e6bc.png)

**Comment by marijnh** [comment]
Which browser are you using? My Chrome and Firefox seem to be fine.

**Comment by krulik** [comment]
I'm using Chrome 63 on OS X 10.11.6

**Comment by marijnh** [comment]
My Chrome takes the charset from the HTML page in this case, but I did notice that the CSS was served without `charset=utf-8` in the content-type header, which was probably the problem. I've adjusted my server config to fix that.
