### ISSUE TITLE
Consider EventListener object variant for Handling Events Section

### ISSUE THREAD

**Issue by thysultan** [marijnh/Eloquent-JavaScript#252]
The lesser know [EventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventListener) object variant is a good "TIL" topic that might be a good fit for the "Handling Events" sections.

**Comment by marijnh** [comment]
I've never really had a situation where I'd prefer to create an object with a method, rather than simply a function, to handle events, since it's almost always more work to set up. So I don't think this is a terribly useful thing to teach people.
