### ISSUE TITLE
Difficult paragraph about prototypes

### ISSUE THREAD

**Issue by krulik** [marijnh/Eloquent-JavaScript#255]
This paragraph in [Chapter 6](http://eloquentjavascript.net/3rd_edition/06_object.html#p_4sWuvx6wkg):

> It is important to understand the distinction between the way a prototype is associated with a constructor (through its prototype property) and the way objects have a prototype (which can be retrieved with Object.getPrototypeOf). The actual prototype of a constructor is Function.prototype since constructors are functions. Its prototype property holds the prototype of instances created through it but is not its own prototype.

I'm an experienced JS dev and instructor and it took me a 2nd slow read to understand your intention (the language semantics are not helpful here either with the confusing choice of "prototype" to describe both the `_proto_` link and the actual container of shared properties). 

WDYT? Maybe a diagram can help here?

**Comment by marijnh** [comment]
Thanks, but this paragraph is intended to clear up exactly the confusing language issue you mention, and I think it does an good job of that—we're not really going to get out from under using the word "prototype" entirely too often and too ambiguously, when describing this stuff. This paragraph already thoroughly considered (it's mostly unchanged from the second edition) and I'm keeping it as it is.
