### ISSUE TITLE
Missing closing bracket ) in chapter 5, 3rd edition

### ISSUE THREAD

**Issue by smilingkite** [marijnh/Eloquent-JavaScript#263]
The function 'average' in chapter 5 is missing a closing bracket. It should be:

function average(array) {
  return array.reduce((a, b) => a + b) / array.length);
}

**Comment by marijnh** [comment]
Thanks for reaching out. But with that added closing parenthesis, there are now more closing than opening parentheses and the code causes an error when you try to run it. So no, I don't think it should be there.
