### ISSUE TITLE
Chapter 10: Broken link to another chapter

### ISSUE THREAD

**Issue by Valeriy-Burlaka** [marijnh/Eloquent-JavaScript#264]
Paragraph https://eloquentjavascript.net/3rd_edition/10_modules.html#h_BOlGLA/wK7  references https://eloquentjavascript.net/3rd_edition/objects#interface , which does not exist.
<img width="752" alt="screenshot 2018-02-02 17 36 03" src="https://user-images.githubusercontent.com/6002242/35744048-9747e140-083f-11e8-98ed-d231c6187a2b.png">

**Comment by marijnh** [comment]
Ah, I had a typo in the link target. Attached patch should fix that.
