### ISSUE TITLE
Chapter 2: Luigis Debt is non-functional

### ISSUE THREAD

**Issue by benschac** [marijnh/Eloquent-JavaScript#270]
http://eloquentjavascript.net/3rd_edition/02_program_structure.html#p_22bMgVFwvP

<img width="1195" alt="screen shot 2018-02-03 at 4 07 24 pm" src="https://user-images.githubusercontent.com/2502947/35771547-96887d74-08fc-11e8-9a70-70961d474dc3.png">

It looks like whatever is compiling the code here thinks that let is a const.

**Comment by marijnh** [comment]
I just fixed this half a minute ago (see #268). If you refresh the page, it should be better.
