### ISSUE TITLE
exercice 3 on recursive function unperfect solution?

### ISSUE THREAD

**Issue by NathanielN** [marijnh/Eloquent-JavaScript#272]
Hi, I understand that your book is adressed to begginers but your exercices helped me toying around with arrow method a bit, so I found your solutions on chapter 3 a bit too trivialised for the actual power of js. Maybe this solution is more optimised and may have more "learning impact". Anyway thanks for your wonderfull book and sorry in advance if I made you loose time for nothing!

function isEven(n) {
  let test = (x) => {
  if (x == 0) return true;
  else if (x == 1) return false;
  else return test(x - 2);
  }
  return n < 0 ? test(-n) : test(n);
}

console.log(isEven(50));
// → true
console.log(isEven(75));
// → false
console.log(isEven(-1));
// → false

**Comment by marijnh** [comment]
That solution isn't actually recursive, so it wouldn't be helpful for an exercise that's about recursion.
