### ISSUE TITLE
Unclear section on parameter scope

### ISSUE THREAD

**Issue by chsm** [marijnh/Eloquent-JavaScript#273]
Hey Marijn,

Huge fan of EJS - have the 2nd edition in print and have been going through the 3rd edition draft online as well.

I think the [example](https://eloquentjavascript.net/3rd_edition/03_functions.html#c_C7Va9Kfw9m) given in the Chapter 3 section on parameter scope is a little unclear.

```javascript
const halve = function(n) {
  return n / 2;
};

let n = 10;
console.log(halve(n * 2));
// → 10
```

The goal of the section is to clarify that if the same variable name is used both outside a function and also within it, only the innermost scope is used and the function will not recognize the variable as declared without. While the code example obviously demonstrates it, I think it is a little unclear because the result of calling `halve(n)` with `n` as the function parameter happens to give the *same* result we would expect if the function *were* accessing the variable from the global scope...

Perhaps an example like the following would better demonstrate the point?

```javascript

let x = 2;
let y = 10;
 
const fraction = function(x, y) {
  let numerator = x; // this reads the *parameters* x and y passed to the function,
  let denominator = y; // not the globally-defined variables outside the function body
  return numerator / denominator;
}

console.log(fraction(3, 10));
// → 0.3 (not 0.2)
```

**Comment by chsm** [comment]
Actually, looking over the section again, perhaps a riff on the [previous code example](https://eloquentjavascript.net/3rd_edition/03_functions.html#c_d7ecKvF5xD) would be more useful, so that there's only *one* change at a time and that the novice may more easily compare the two to see what the difference is.

The code example for introducing scoping:

```javascript
let x = 10;
if (true) {
  let y = 20;
  var z = 30;
  console.log(x + y + z);
  // → 60
}
// y is not visible here
console.log(x + z);
// → 40
```

Proposed example to show that value defaults to innermost scope for conflicting variable names:

```javascript
let x = 10;
if (true) {
  let x = 5;
  let y = 20;
  var z = 30; // z is globally visible because it's declared with `var`
  console.log(x + y + z); // this will use the 'inner' value for x
  // → 55
}
// this will use the 'outer' value for x instead
console.log(x + z);
// → 40
```

**Comment by marijnh** [comment]
Attached patch changes the example so that the number 10 doesn't occur twice, which indeed makes it easier to tell the variables/values apart.
