### ISSUE TITLE
Misplaced semicolons

### ISSUE THREAD

**Issue by chsm** [marijnh/Eloquent-JavaScript#274]
Hey Marijn,

Founds some semicolons lurking in places I did not expect to find them. Some are legal but unnecessary and possible style violations, depending which guide you prefer.

[Here](https://eloquentjavascript.net/3rd_edition/02_program_structure.html#c_Rdlc+hwgyM):

```javascript
let yourName;
do {
  yourName = prompt("Who are you?");
} while (!yourName); //  <---
console.log(yourName);
```

[And here](https://eloquentjavascript.net/3rd_edition/03_functions.html#c_JW7vLBZMWv):

```javascript
const square = function(x) {
  return x * x;
}; <---

console.log(square(12));
// → 144
```

[And also here](https://eloquentjavascript.net/3rd_edition/03_functions.html#c_8fTeYA4ABW):

```javascript
const makeNoise = function() {
  console.log("Pling!");
}; <---

makeNoise();
// → Pling!

const power = function(base, exponent) {
  let result = 1;
  for (let count = 0; count < exponent; count++) {
    result *= base;
  }
  return result;
}; <---

console.log(power(2, 10));
// → 1024
```

In fact, there are several more throughout Chapter 3; guessing they're just leftovers from sketching out the examples that were not removed yet.

**Comment by marijnh** [comment]
These are all required by the grammar if you ignore automatic semicolon insertion, and my policy in the book is to include every semicolon.
