### ISSUE TITLE
Exercise 8.2 variable 'var'

### ISSUE THREAD

**Issue by victorze** [marijnh/Eloquent-JavaScript#277]
[Exercise 8.2](http://eloquentjavascript.net/3rd_edition/code/#8.2)

![captura](https://user-images.githubusercontent.com/22132891/35822380-1cef0288-0a7a-11e8-9e76-8a586802525d.PNG)

**Comment by marijnh** [comment]
Good point. Attached patch makes that (and a few more `var`s) a `let`.
