### ISSUE TITLE
Chapter 9 related typos

### ISSUE THREAD

**Issue by joulecpa** [marijnh/Eloquent-JavaScript#279]
http://eloquentjavascript.net/3rd_edition/09_regexp.html#p_YUOJEGEtSI

The example prior uses the exec function but this following line refers to the match function.

http://eloquentjavascript.net/3rd_edition/09_regexp.html#p_mwlBKfUu5D

whether it is a comment or an _emty_ line

http://eloquentjavascript.net/3rd_edition/code/#9.3

The solution in the sandbox has a ReferenceError: s is not defined error when run due to having s instead of str

**Comment by marijnh** [comment]
Thanks. Should be better with patch 9e08a7e
