### ISSUE TITLE
Chapter 11- typo/reword

### ISSUE THREAD

**Issue by tuna15** [marijnh/Eloquent-JavaScript#280]
Might need to reword the sentence in bold below.

"The solution to this problem, in a synchronous system, is to start additional threads of control. A thread is another **running program whose execution the operating system may interleave** with other programs—since most modern computers contain multiple processors, multiple threads may even run at the same time, on different processor. A second thread could start the second request, and then both threads wait for their results to come back, after which they resynchronize to combine their results."

**Comment by marijnh** [comment]
Why do you think that?

**Comment by tuna15** [comment]
It was a bit awkward while reading last night but not as much so on rereading this morning.  

Perhaps- "A thread is another program whose execution is interleaved with other programs by the operating system -..." or " A thread is another program whose execution _by_ the operating system my interleave with other programs..."

**Comment by marijnh** [comment]
How about _whose execution may be interleaved with other programs by the operating system_?

**Comment by tuna15** [comment]
Great.  That reads much easier to me.

**Comment by marijnh** [comment]
Done in attached patch!
