### ISSUE TITLE
Regular Expressions. Space not necessary.

### ISSUE THREAD

**Issue by victorze** [marijnh/Eloquent-JavaScript#282]
http://eloquentjavascript.net/3rd_edition/09_regexp.html#p_/5YU/Qo2Np

I think space is not necessary.

![captura](https://user-images.githubusercontent.com/22132891/35864900-0f4b3780-0b21-11e8-8904-5702523fd037.PNG)

**Comment by marijnh** [comment]
The original example had `Van Gogh, Vincent` in there, but yeah, I guess for the current input I can simplify it. Done in attached patch.
