### ISSUE TITLE
Chapter 2 - Conditional Execution code snippets return 0 with blank input.

### ISSUE THREAD

**Issue by vjvalentin** [marijnh/Eloquent-JavaScript#285]
The code snippets in chapter 2 under Conditional Execution allow the user to supply no input and do not correctly test if no number is given. Empty strings are coerced to 0, so it's giving misleading results.

**Comment by marijnh** [comment]
I'm aware of this, but making the example behave differently would require making the code more complicated. Since this behavior isn't a serious problem, I'm leaving it as it is.
