### ISSUE TITLE
Values section: explain volatile storage

### ISSUE THREAD

**Issue by voltagex** [marijnh/Eloquent-JavaScript#293]
https://eloquentjavascript.net/3rd_edition/01_values.html#h_sVZPaxUSy/

Should both volatile and nonvolatile storage have an explanation here?

```
Imagine a sea of bits. An ocean of them. 

A typical modern computer has more than 30 billion bits in its volatile data storage. 

Nonvolatile storage *(the hard disk or equivalent)* tends to have yet a few orders of magnitude more.
```

**Comment by marijnh** [comment]
Yeah, good point, I've added a parenthetical for volatile storage in attached patch.
