### ISSUE TITLE
Code example has redundant `else` block

### ISSUE THREAD

**Issue by sangupta** [marijnh/Eloquent-JavaScript#295]
The `else` block in the code example below is redundant - as it is immediately preceded by a `return` statement. Code sample is as under:

![image](https://user-images.githubusercontent.com/883042/35900471-f69a797e-0b86-11e8-9701-a689ad2093c8.png)

The code block is available on this page: https://eloquentjavascript.net/3rd_edition/00_intro.html

There are other occurrences where the same pattern is used. I can help send a PR if needed.

**Comment by MaxSchumacher** [comment]
You are right in this particular instance, but Eloquent Javascript is a beginner's book, so I think it is sensible to spell out the full example. Without memoization this just a toy implementation anyway.

**Comment by sangupta** [comment]
Agreed. Just a thought around adding a comment to the code to let reader's know that they may skip it out.

**Comment by marijnh** [comment]
Yeah this is intentional. Sure it's technically redundant, but it's entirely harmless and makes the code easier to scan. You'll see more code like that throughout the book.
