### ISSUE TITLE
The third edition page features a second edition cover

### ISSUE THREAD

**Issue by revolter** [marijnh/Eloquent-JavaScript#296]
[This page](https://eloquentjavascript.net/3rd_edition) features this image:

![third edition cover](https://eloquentjavascript.net/3rd_edition/img/cover.png)

which says "second edition" instead of "third edition".

**Comment by marijnh** [comment]
I know. It'll be replaced when the new cover is done!

**Comment by revolter** [comment]
Thought you missed it so I just wanted to make sure 😄
