### ISSUE TITLE
Gitter-based dicussion forum for readers?

### ISSUE THREAD

**Issue by kumarashwin** [marijnh/Eloquent-JavaScript#298]
I trudged through the 2nd Ed. alone and what I learned there was instrumental in helping me start a career as a web developer.

I'm sure my background in Software; my degree in Information Systems, was key in helping me through the book when things got tough. I'm sure that for many others, it was not the same and may continue to be so.

Someone already mentioned on HackerNews, in the discussion about the 3rd Ed., that they would like to have a forum or a place for the community to discuss questions they might have pertaining to the topics in this book.

**I suggest [Gitter](http://gitter.im/) since it's a heavily-used platform by other major open-source efforts on GitHub, and you only need your GitHub account to use it and participate.**

**Comment by marijnh** [comment]
I'm not really a user of chat-style communication channels myself, but I guess it might work if I set up the channel and add a link to it on the book's website. Not sure about gitter, though. I have channels for some other projects and the interface isn't great (fails at very basic tasks like scrolling new messages into view when you open the page). But I guess at least the barrier to entry is lower than with IRC. Do you know of any other alternatives?

**Comment by kumarashwin** [comment]
@marijnh 

Even if you aren't very active on the chat (not that you don't have to be, but I totally understand), I feel like it'd be a great coalescing point for the community reading your book. For e.g., if you get a rush of people from, say, the FreeCodeCamp community, they might land _en masse_ on your book and then desire a place to ask pointed questions.

For other alternative, I'll do a bit more research. I suggested Gitter early since it is possibly the easiest just because it requires only a GitHub account and you don't need to go search for a channel since the channel names and URLs correlated directly to the GitHub repos.

(Also, it's kind of surreal to be having this discussion with the person to who I owe so much credit for having helped me start my career as a developer. 😊 Thanks for what you do!)

**Comment by JBallin** [comment]
@marijnh IF interested in chat, gitter is awesome on the user's end (and is quite popular with similar projects, slack has too much going on). 

https://sameroom.io allows for integration between different chat apps if you prefer to monitor gitter through IRC. Their site allows you to see your different chat options as well.

**Comment by marijnh** [comment]
So I just tried to create a new room. First, it was rather complicated to find the link to do that, because `gitter.im` kept redirecting me to the last room I was in rather than showing some kind of front page, and the link to 'home' was buried in the user menu. Then, the form for creating a new room just didn't work (button does nothing, console shows JavaScript errors).

... It's a little hard for me to put trust in a system that is so obviously poorly managed.

**Comment by MadLittleMods** [comment]
@marijnh Gitter developer here 👋 

It looks like you need to create the `marijnh` community first which is started with the `+` button on the menu bar(bottom-left)

![](https://i.imgur.com/URlKUhC.png)

You can create a room with the "Add a room" button at the bottom of the left menu (no need to go to user home page).

![](https://i.imgur.com/ns0dA1n.png)

---

What JavaScript errors are you seeing?

**Comment by JBallin** [comment]
↑ @marijnh I looped in Gitter support, hope they can be helpful here!

**Comment by kumarashwin** [comment]
Think we can close this issue now.

**Comment by marijnh** [comment]
Okay, clicking 'create a community' landed me on a different interface that worked. We have a room now at https://gitter.im/Eloquent-JavaScript/Lobby, and I've linked it from the book's front page.
