### ISSUE TITLE
Ch. 20 outdated package reference

### ISSUE THREAD

**Issue by akindofcode** [marijnh/Eloquent-JavaScript#299]
In the **Installing with NPM** section (3rd Edition draft) there is a reference to the figlet package, should be the ini package instead as the example was changed from the 2nd edition of the book.

> After running npm install, NPM will have created a directory called node_modules. Inside that directory will be an ini directory, which contains the library. When we run node and call **require("figlet")**, this library is loaded, and we can call its text method to draw some big letters.

**Comment by marijnh** [comment]
Thanks for spotting that. Attached patch fixes it.
