### ISSUE TITLE
Chapter 15 - Link to another chapter incomplete

### ISSUE THREAD

**Issue by PolarisTLX** [marijnh/Eloquent-JavaScript#302]
Chapter 15 - Section "Key Events":

"We’ll come back to form fields in Chapter ?. "

1. The ? should be replaced to "18"  (this seems to be a redisigned chapter and called "HTTP and Forms".
2. The link, which is currently "http://eloquentjavascript.net/3rd_edition/forms"
Should be replaced to "http://eloquentjavascript.net/3rd_edition/18_http.html"

**Comment by marijnh** [comment]
Thanks! I should probably set up a script to automatically check that all links point somewhere. Attached patch fixes this one.
