### ISSUE TITLE
Possibly rewrite of short paragraph in Chapter 9

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#305]
I began studying the 2nd edition of Eloquent JavaScript in late 2017, and am now continuing in the 3rd edition. I can't say enough good things about this book. Thank you. I very much appreciate all your efforts. 

In chapter 9, in the section "Parsing an INI file", there is a paragraph that states:

"Our task is to convert a string like this into an array of objects, each with a name property and an array of settings. We’ll need one such object for each section and one for the global settings at the top."

To me, this does not accurately describe what the code creates, which is an object with a property for each global setting and a property named for each section which in turn contains an object with properties for its settings. 

I hope this is helpful, and that I'm not misinterpreting. 

Thanks, 

Dave

**Comment by marijnh** [comment]
Good point—the code used to work differently, and this still describes the old output format. Patch 4a2aaef changes it.
