### ISSUE TITLE
Chapter 9 Summary

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#308]
The summary states:

"/x{2,4}/   Between two and four occurrences"

Would it be better to say 

"Between two and four occurrences, inclusive"

or as you state earlier in the chapter

"the element must occur at least twice and at most four times"

**Comment by marijnh** [comment]
How about "two to four occurrences"?

**Comment by dhollinden** [comment]
perfect. thanks

**Comment by marijnh** [comment]
Done in attached patch! Thanks for pointing it out.
