### ISSUE TITLE
Slightly confusing wording about bits per character

### ISSUE THREAD

**Issue by gajeam** [marijnh/Eloquent-JavaScript#309]
Great book. Just a quick thing. In Chapter 2, you have this quote:

> And that’s what JavaScript does. But there’s a complication: **JavaScript’s representation uses 16 bits per number**, and there are more than 2^16 different characters in Unicode (about twice as many, at this point). 

This makes it seem like Javascript uses 16 bits to represent every number (even though you say otherwise earlier.) However, that's only true for the number underlying characters. Perhaps you could say it like this:

> And that’s what JavaScript does. But there’s a complication: **JavaScript’s numerical representation of characters is only 16 bits long**, and there are more than 2^16 different characters in Unicode (about twice as many, at this point). 

Feel free to close if this is too persnickety. Thanks!

**Comment by marijnh** [comment]
Attached patch should help with this.
