### ISSUE TITLE
Additions to Chapter 9 summary list

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#313]
It'd be nice if these were included in the Chapter 9 summary list.

\D  A character that is not a digit
\W  A nonalphanumeric character
\S  A nonwhitespace character

Thanks

**Comment by marijnh** [comment]
Hi. Thanks for the suggestion, but since these are relatively rarely used, and have been mentioned before, I intentionally didn't put them in the summary table to keep its size reasonable.
