### ISSUE TITLE
npm should be lowercase throughout

### ISSUE THREAD

**Issue by EmmaRamirez** [marijnh/Eloquent-JavaScript#315]
Throughout the book, NPM should be stylized as "npm" (https://docs.npmjs.com/getting-started/what-is-npm), (https://twitter.com/chriscoyier/status/896051713378992130)

**Comment by marijnh** [comment]
I'm aware of the preference of the maintainers, but for stylistic reasons (keeping the text readable and avoiding confusion by not randomly flaunting notation conventions) I'm ignoring that.
