### ISSUE TITLE
code in sandbox does not give described result

### ISSUE THREAD

**Issue by smilingkite** [marijnh/Eloquent-JavaScript#316]
When I run the answer-code in node on my own pc (node 7.6.0 - same after using node  8.9.4) in exercise 6.2 it gives: 

List {
  value: 10,
  rest: List { value: 20, rest: List { value: undefined, rest: undefined } } }
[ 10, 20, 30 ]
1

Sandbox gives something closer to the expected result:
{value: 10, rest: {value: 20, rest: {value: undefined, rest: undefined}}
[ 10, 20, 30 ]
1

Expected result:
{value: 10, rest: {value: 20, rest: null}}
[ 10, 20, 30 ]
1

**Comment by marijnh** [comment]
Ah, right, the example output still refers to the thing I did before I added `List.empty`. That's what the `{value: undefined, rest: undefined}` refers to. This is awkward, and I wasn't too happy about that exercise before, so I've replaced it with another one in attached patch.
