### ISSUE TITLE
small grammar mistake

### ISSUE THREAD

**Issue by smilingkite** [marijnh/Eloquent-JavaScript#318]
Chapter 10, first exercise, hints:

On top of that, depending on NPM packages means you have to make sure they are installed, you have to _distributing_ them with your program, and you might have to periodically upgrade them.

distributing should be distribute:

On top of that, depending on NPM packages means you have to make sure they are installed, you have to _distribute_ them with your program, and you might have to periodically upgrade them.

**Comment by marijnh** [comment]
Thanks! Fixed in attached patch.
