### ISSUE TITLE
Comparing NaN to true or false produces false as with itself 

### ISSUE THREAD

**Issue by zeselassie** [marijnh/Eloquent-JavaScript#319]
http://eloquentjavascript.net/3rd_edition/01_values.html#p_N4OuWeYOwF

When I experiment in the console: true == NaN, false == NaN and as it is stated in the text, NaN == NaN, all produce false. But the following sentence under the heading  "Automatic type conversion" says converting NaN to boolean counts as false.

The rules for converting strings and numbers to Boolean values state that 0, NaN, and the empty string ("") count as false, while all the other values count as true.

**Comment by marijnh** [comment]
Yes. There's a difference between _comparing_ and _converting_. `if (NaN) console.log("nan is true")` won't print anything, for example.
