### ISSUE TITLE
Chapter 7 typo

### ISSUE THREAD

**Issue by taylorham** [marijnh/Eloquent-JavaScript#320]
First, thanks so much for the incredible work you've put in to this book and its revisions! It really is an invaluable tool for any JS dev.

In the Chapter 7 section "Persistent Data" you have a typo on the last line of the second-to-last paragraph:

> "Anything that **_making_** your system easier to understand makes it possible to build a more ambitious system."

I assume this should be "Anything that **_makes_**..."

Thanks again!

**Edit:** Just found another one! In "The Mail Truck's Route" section, last line of the second paragraph:

> "The robot keeps the rest of its route in its memory, and **_drop_** the first element every turn."

Seems like this should be "...and **_drops_** the first..."

**Comment by JBallin** [comment]
I'll submit a PR for this shortly

**Comment by marijnh** [comment]
Thanks for reporting that. Solved via #321
