### ISSUE TITLE
chapter 5 answers wrong?

### ISSUE THREAD

**Issue by rakkarage** [marijnh/Eloquent-JavaScript#324]
questions:
http://eloquentjavascript.net/3rd_edition/05_higher_order.html
answers:
https://eloquentjavascript.net/code/#5.3

5.1, question: flatten, answer: flatten, ok
5.2 question: loop, answer: mother child age difference, wtf
5.3 question: every, answer: historical life expectancy, wtf
5.4 question: writing direction, answer: every, wtf

maybe for other version idk
thanks

**Comment by marijnh** [comment]
You're at the wrong code sandbox, you want https://eloquentjavascript.net/3rd_edition/code/#5.3 . Yes, I know some links in the book link to the other one, since its current URL is temporary.
