### ISSUE TITLE
3rd edition, Chapter 5, Abstracting repetition - unnecessary parameter

### ISSUE THREAD

**Issue by milkevich** [marijnh/Eloquent-JavaScript#326]
http://eloquentjavascript.net/3rd_edition/05_higher_order.html#c_p03rPqGmn9
Anonymous arrow function doesn't use parameter `i` from repeat function.
`let message = "Wow";
repeat(5, i => {
  message += "!";
});
console.log(message);
// → Wow!!!!!`
Maybe it would be more clearer `repeat(5, () => {` ?

Thank you. I very much appreciate all your efforts.

**Comment by JBallin** [comment]
I'll submit a PR shortly

**Comment by marijnh** [comment]
See my comment on #328
