### ISSUE TITLE
Chpater 13 typo

### ISSUE THREAD

**Issue by hyfed** [marijnh/Eloquent-JavaScript#329]
I  believe that there's a typo in the last paragraph of THE WEB section right before section HTML begins

> Then, using the ((HTTP)) protocol, it makes a connection to the server at that address and asks for the resource **/12_browser.html**. If all goes well, the server sends back a document, which your browser then displays on your screen.

I assume it should:    **/13_browser.html**

**Comment by marijnh** [comment]
Thanks! There was a similar issue in Chapter 18. Attached patch fixes them.
