### ISSUE TITLE
The recursion exercise link goes to the recursion section

### ISSUE THREAD

**Issue by ericandrewlewis** [marijnh/Eloquent-JavaScript#334]
Hey Marijn 👋 It's been great reading your book!

In [chapter three](http://eloquentjavascript.net/3rd_edition/03_functions.html#h_jxl1p970Fy) there's a section called "Recursion" and an exercise called "Recursion". They both produce the same link [http://eloquentjavascript.net/3rd_edition/03_functions.html#h_jxl1p970Fy](http://eloquentjavascript.net/3rd_edition/03_functions.html#h_jxl1p970Fy), which I assume is because the anchor hashing algorithm in the HTML generator.

I'd bet this is a bug in whatever that HTML generator is, but thought I'd surface this behavior. Perhaps it could be avoided by renaming either the exercise or the section.

**Comment by marijnh** [comment]
Oh, good point. Indeed, it just hashes the content of the element. The HTML generator is a custom one, so this is the right repository. Attached patch uses a different prefix for H2 and H3 section headings, working around this specific problem.
