### ISSUE TITLE
Grammatical Error: takes an iteratable object as argument and...

### ISSUE THREAD

**Issue by paul-kline** [marijnh/Eloquent-JavaScript#336]
that takes an iteratable object as **an** argument and creates a group
[http://eloquentjavascript.net/3rd_edition/06_object.html#p_CbJ60eqr+J](http://eloquentjavascript.net/3rd_edition/06_object.html#p_CbJ60eqr+J)

**Comment by marijnh** [comment]
Thanks, but I think the way I have it is also grammatically correct.
