### ISSUE TITLE
Chapter 15 - Exercise "Tabs" - Inconsistent wrapping <div> to sandbox solution

### ISSUE THREAD

**Issue by PolarisTLX** [marijnh/Eloquent-JavaScript#337]
In the last exercise of Chapter 15, "TABS",  the problem is laid out as:

    <tab-panel>
         <div...
         <div...
    </tab-panel>
    <script>
        .
        .
      asTabs(document.querySelector("tab-panel"));
    </script>

But the solution in the sandbox is laid out as:

    <div id="wrapper">
         <div...
         <div...
    </div>
    <script>
         .
         .
         asTabs(document.querySelector("#wrapper"));
    </script>`

Recommend remaining consistent with "\<div id="wrapper"\>", which is the same as it was in the 2nd Edition.

**Comment by marijnh** [comment]
Thanks for noticing that! Attached patch makes the solution match the exercise.
