### ISSUE TITLE
CH. 5 strings and character codes - suggestion on reformatting example code

### ISSUE THREAD

**Issue by Nick-Gottschlich** [marijnh/Eloquent-JavaScript#338]
Hey there,

I'm going through the third edition right now. At [this point](https://eloquentjavascript.net/3rd_edition/05_higher_order.html#p_aEEZgRpp75) there is a code block formatted like this:

```javascript
function characterScript(code) {
  for (let script of SCRIPTS) {
    if (script.ranges.some(([from, to]) => code >= from &&
                                           code < to)) {
      return script;
    }
  }
  return null;
}
```

IMO it is much easier to read like this:

```javascript
function characterScript(code) {
  for (let script of SCRIPTS) {
    if (script.ranges.some(([from, to]) => {
      return (code >= from && code < to);
    })) {
      return script;
    }
  }
  return null;
}
```

The switch from the fat arrow (`=>`) to greater than or equals (`>=`) will definitely confuse people, separating them with brackets makes it much more readable.

Awesome book, I'm learning a ton going through it!

**Comment by dhollinden** [comment]
"The switch from the fat arrow (=>) to greater than or equals (>=) will definitely confuse people"

I stumbled on that for a bit.

**Comment by marijnh** [comment]
Attached  patch makes this change.

**Comment by dhollinden** [comment]
Thumbs up. Thanks.
