### ISSUE TITLE
Chapter 1 "automatic type conversion"

### ISSUE THREAD

**Issue by HaoyangFan** [marijnh/Eloquent-JavaScript#339]
> The rules for converting strings and numbers to Boolean values state
that 0, NaN, and the empty string ("") count as false

However, when I run that using node(v9.2.0), I got
`console.log(false == NaN); //it looks like NaN does not evaluate to false`

Is it a problem? I am new to JS so I am not quite sure about that

**Comment by skotniczny** [comment]
You can find very detailed explanations about conversion and comparisons in [You Don't Know JS: Types & Grammar](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch4.md)

**Comment by marijnh** [comment]
The sentence refers to _conversion to boolean_, not comparison with `==`. As in, if you do something like `if (NaN) ...`, the body of the `if` won't run.

**Comment by HaoyangFan** [comment]
Hi I check for some resources, using `==` will trigger type coercion, then why in that case `NaN` is not type casted to `false`?

**Comment by marijnh** [comment]
It will convert false to 0 and compare 0 and NaN

**Comment by HaoyangFan** [comment]
Oh it makes sense. Thanks for help
