### ISSUE TITLE
Code sandbox URL in first page of chapter 4

### ISSUE THREAD

**Issue by peymanslh** [marijnh/Eloquent-JavaScript#340]
In first page of chapter 4 (page 64) in PDF version of 3rd edition, code sandbox URL is wrong and line cross the page edge, when clicking on link going to this URL `http://eloquentjavascript.net/code%5Beloquentjava`;

### Screenshot
![screen shot](https://user-images.githubusercontent.com/7171098/36351146-6e3bc74e-14ba-11e8-85b7-e82e6ce1fd9f.jpg)

**Comment by marijnh** [comment]
Thanks for spotting that. Attached patch puts the link in the proper format.
