### ISSUE TITLE
CH 4: array slice

### ISSUE THREAD

**Issue by raduflp** [marijnh/Eloquent-JavaScript#342]
> When the end index is not given, slice will take all of the elements **after** the start index.

this would suggest that `[0, 1, 2, 3, 4].slice(2)` should produce `[3, 4]` which is incorrect.

**Comment by guifrrs** [comment]
"Another fundamental array method is slice, which takes start and end indices and returns an array that has only the elements between them. The start index is inclusive, **the end index exclusive.**" 

Actually, that part is right before the example, but I get your point.

**Comment by kapreski** [comment]
it's clearly stated before the example:
 "The start index is inclusive, the end index exclusive."
.slice(2) the index 2 is included..

**Comment by raduflp** [comment]
@guifrrs @kapreski i was just trying to think from the perspective of a newcomer to JS. When presenting a different scenario with only one argument one might not make a connection with the preceding inclusiveness note. 
So I think it would be reasonable to paraphrase in order to eliminate any confusion.

**Comment by marijnh** [comment]
I think this should be clear from context [now](http://eloquentjavascript.net/04_data.html#p_xl0kBHXnu2).
