### ISSUE TITLE
crow_tech or crows?

### ISSUE THREAD

**Issue by homerhanumat** [marijnh/Eloquent-JavaScript#344]
3rd Edition Chapter 11 mentions imports from a crow_tech module but the code for this chapter contains no such file.  Is it crows.js?

**Comment by marijnh** [comment]
As it was, that module wasn't loadable in Node, so it'd be hard to use separately anyway. Attached patch improves this, and renames it to crow-tech to prevent confusion.

**Comment by homerhanumat** [comment]
Thanks.  Perhaps include the [polyfill for Object.values](https://github.com/tc39/proposal-object-values-entries/blob/master/polyfill.js) in the file as well, for the time being?

**Comment by marijnh** [comment]
What browser are you using that can handle the syntax from the book but doesn't have Object.values?

**Comment by homerhanumat** [comment]
I have been running code samples with node.  But if assumed use is in browser then no worries, I'll make my own adjustments.

**Comment by marijnh** [comment]
It seems Node introduced Object.values in version 7, which has been stable for a while, so maybe upgrade?

**Comment by homerhanumat** [comment]
Ah,  now I see:  turns out VSCode was using the "system" node (v6.9.5).
