### ISSUE TITLE
Chapter 16 - Actors have four properties

### ISSUE THREAD

**Issue by PolarisTLX** [marijnh/Eloquent-JavaScript#347]
In the "ACTORS" section it is written:

"Their interface **_consists of four properties_**. Firstly the pos property holds the coordinates...."

It then describes 3 properties ("pos", "size" and "type"), and describes 2 methods ("update" and "create").
<br></br>
Perhaps it was meant to also include the property "speed":
"It has a property speed that stores its current speed, which will help simulate momentum and gravity.".
<br>
Or, since not all Actors have "speed" (coins don't), perhaps it was meant to read: 
"Their interface consists of three properties" or "three properties and two methods".
<br></br>
The portion on the "Vec" class might also be better placed as the first thing, or last thing, in the section?

**Comment by marijnh** [comment]
`create` is a static method, not a property of actor objects.

We'll be creating vectors in all the actor constructors, so I think it makes sense to define that first.
