### ISSUE TITLE
Missing a space in chapter 2. 

### ISSUE THREAD

**Issue by JayGDaBoss6** [marijnh/Eloquent-JavaScript#349]
Under your explanation for the console.log function in chapter 2 you forgot the trailing space at the end of  the string. 

`let x = 30;
console.log("the value of x is", x);
// → the value of x is 30`

Should be:

`let x = 30;
console.log("the value of x is ", x);
// → the value of x is 30`

**Comment by marijnh** [comment]
`console.log` will add a space between its arguments. Try it.

**Comment by JayGDaBoss6** [comment]
Cool. Thanks :)
