### ISSUE TITLE
Chapter 4 Exercises, A List

### ISSUE THREAD

**Issue by kardmeister** [marijnh/Eloquent-JavaScript#350]
"[nth] returns the element at the given position in the list"

do positions in a list start with 1 as the first element or 0, like arrays? i can see that this is implicit in the given call to nth in the exercise but it could be specified in the instructions--for those of us who don't like to assume ;)

thanks.

**Comment by marijnh** [comment]
Good point. Patch 9a44eb8 tries to clarify this.
