### ISSUE TITLE
is SCRIPTS.js missing?

### ISSUE THREAD

**Issue by kapreski** [marijnh/Eloquent-JavaScript#354]
maybe it's me, but I couldn't locate the "SCRIPTS" binding  in the sandbox of chapter 05 'Higher-Order Functions'
any idea?

**Comment by marijnh** [comment]
Where did you look? `console.log(SCRIPTS)` in any of the code snippets does show me an array. The file that defines the array is listed at http://eloquentjavascript.net/3rd_edition/code/#5 . Maybe you landed on the code sandbox for the 2nd edition?

**Comment by kapreski** [comment]
I think I clicked on this link : https://eloquentjavascript.net/3rd_edition/05_higher_order.html#p_RWVZnsc/dS
probably went to the old sandbox of version 2
thanks for the new link

**Comment by marijnh** [comment]
Yeah, there are some absolute links in the book — they will become valid once I move it from /3rd_edition to the top of the domain (hopefully somewhere next week).
