### ISSUE TITLE
Ch. 6, Methods, Implicit "this" binding

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#356]
As a student of this book, and a relative newbie, I struggled to understand the first clause of the following:

"Since each function has its own implicit this binding, you cannot refer to the this of the wrapping scope in a regular function defined with the function keyword."

I've come to understand it this way, and if this is correct, perhaps you might consider a revision.

"Since each function's this binding is implied by how it is invoked, you cannot refer to the this of the wrapping scope in a regular function defined with the function keyword."

Thank you

**Comment by marijnh** [comment]
Does the change in patch 3e0a2aa clarify this for you?

**Comment by dhollinden** [comment]
Yes, it does. Wonderful. Thank you.
