### ISSUE TITLE
Ch. 6, Methods, "this" binding for arrow functions

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#357]
In the following paragraph

"Arrow functions are different—they do not bind their own this, and thus you can do something like the following code, which references this from inside a local function."

For me, it would be helpful to state how "this" is actually bound, perhaps like the following:

Arrow functions are different—they do not bind their own this. Instead, this retains the value of the enclosing lexical context's this. You can, therefore, do something like the following code, which references the enclosing this from inside a local function.

I took the language "this retains the value of the enclosing lexical context's this" from MDN Web Docs.

Thank you

**Comment by mikegowen** [comment]
+1

**Comment by marijnh** [comment]
Attached patch should help here.

**Comment by dhollinden** [comment]
Great. Thank you!
