### ISSUE TITLE
Chapter 6 - *code wont run

### ISSUE THREAD

**Issue by kenitohenry** [marijnh/Eloquent-JavaScript#358]
code block after ## class notation wont run -- no speak method?  is not called and no line value is passed.

**Comment by marijnh** [comment]
You mean the one that starts with `class Rabbit`? That one works for me. If not that code, please be more specific.

**Comment by kenitohenry** [comment]
yes that one, when I try to run nothing console.logs, only when I pass in a line parameter it works

**Comment by kenitohenry** [comment]
![image](https://user-images.githubusercontent.com/32582494/36544673-04ea1c98-17b5-11e8-8ba9-8b08d56121e5.png)
![image](https://user-images.githubusercontent.com/32582494/36544775-4399b304-17b5-11e8-8493-942b9f3a04c4.png)

**Comment by marijnh** [comment]
Yes, that is as it should be — the code just defines the class and two instances, so it won't log anything.
