### ISSUE TITLE
Ch. 6 – Why use parentheses in the class shorthand example?

### ISSUE THREAD

**Issue by mikegowen** [marijnh/Eloquent-JavaScript#362]
http://eloquentjavascript.net/3rd_edition/06_object.html#c_JKY9zuey2L

```
let object = (new class { getWord() { return "hello"; } });
console.log(object.getWord());
// → hello
```

If I'm not mistaken, the outer parentheses aren't necessary here. If they are, maybe call attention to them. If they aren't necessary, it would seem better to leave them off as this expression would then more obviously map to how you'd write a function expression (a comparison you already make alongside the code).

P.S. Chapter 6 is pretty tough. I was warned of this chapter before I started the book, and it didn't disappoint :) I was going to submit a big issue with a few reasons why it's difficult and how it could be addressed, but I'll try to address them in individual issues.

**Comment by marijnh** [comment]
You are right, those can be removed. See attached patch.

> I was warned of this chapter before I started the book,

It was worse in the 2nd edition ;)

**Comment by mikegowen** [comment]
I agree, I've been through about 3/4 of the 2nd edition. Started over when the 3rd came out and it has definitely been smoother. Kudos.
