### ISSUE TITLE
Wide content images don't fit in the container

### ISSUE THREAD

**Issue by guryanov-a** [marijnh/Eloquent-JavaScript#368]
e.g., the image of octopus in the 2nd chapter:

![wide content images don t fit in the container](https://user-images.githubusercontent.com/12662274/36629446-0477ffce-1980-11e8-8283-c9853fb879ea.png)

The second edition of the book has the following styles for images (which the 3rd edition doesn't have):

```
div.image {
    max-width: 640px;
    margin: 0 30px;
}

div.image img {
    max-width: 100%;
}
```

**Comment by marijnh** [comment]
The problem was that I changed the HTML output to use `<figure>` instead of `<div class=image>`, and updated the CSS to match, but failed to rebuild some of the HTML pages. Should be better now!
