### ISSUE TITLE
Ch. 5, Script data set: incorrect link

### ISSUE THREAD

**Issue by guryanov-a** [marijnh/Eloquent-JavaScript#369]
http://eloquentjavascript.net/3rd_edition/05_higher_order.html#p_RWVZnsc/dS - the paragraph contains a link which refers to the sandbox of the 2nd edition of the book (`http://eloquentjavascript.net/code/#5` instead of `http://eloquentjavascript.net/3rd_edition/code/#5`) and in the sandbox of the 2nd edition there is no `scripts.js` which is described in the paragraph.

**Comment by marijnh** [comment]
Yes, that's true. I'll migrate the 3rd edition to the top level later this week, at which point this'll resolve itself.

**Comment by marijnh** [comment]
The 3rd edition is now the default edition, fixing this.
