### ISSUE TITLE
Grammatical Error: tends be easy to test

### ISSUE THREAD

**Issue by paul-kline** [marijnh/Eloquent-JavaScript#370]
Possible fix:
''tends **to** be easy to test''

Chapter 8
[http://eloquentjavascript.net/3rd_edition/08_error.html#p_zmvP6RI0eK](http://eloquentjavascript.net/3rd_edition/08_error.html#p_zmvP6RI0eK)

**Comment by marijnh** [comment]
Thanks! Fixed by attached patch.
