### ISSUE TITLE
Typo - Chapter 11 - Asynchronous Programming

### ISSUE THREAD

**Issue by PolarisTLX** [marijnh/Eloquent-JavaScript#375]
I believe this is just a tiny typo but thought you'd want to have them corrected:

In Chapter 11, about 1/5th way down, in Callbacks section:

"The example adds support for "note" requests, which just &nbsp; _**sends**_  &nbsp; a note to a given nest."

**Comment by marijnh** [comment]
Thanks for opening an issue! Fixed in attached patch.
