### ISSUE TITLE
Ch 10, Packages - small grammatical error

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#385]
In this sentence, 

"It may contain one or more modules, and has information about you which other packages it depends on."

I believe the "word" you should be deleted. 

Just confirming: do you want small errors like this to be submitted?

Thanks

**Comment by marijnh** [comment]
Thanks! Fixed in attached patch.

> Just confirming: do you want small errors like this to be submitted?

Absolutely—getting these kind of typos and small mistakes pointed out is very valuable.
