### ISSUE TITLE
Ch 10 errors in sandbox

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#386]
I'm looking at the code for the const weekDay = function() 

1. Activate the editor

2. Run code -> console log shows expected result

3. Run code a second time -> console.log shows "Uncaught SyntaxError: Identifier 'weekDay' has already been declared (line 1)"

This is happening in other places as well. 

Thanks

**Comment by dhollinden** [comment]
In case this is helpful:

Nearly up to date! Relaunch Google Chrome to finish updating.
Version 63.0.3239.132 (Official Build) (64-bit)

macOS Sierra version 10.12.6

**Comment by marijnh** [comment]
This isn't happening for me (on Chrome). Could it be that your browser has the old code cached? Does a cmd-r refresh help?

**Comment by dhollinden** [comment]
Ah, shoot, that was it. I should have thought of that. Sorry for the bother! :)

**Comment by marijnh** [comment]
Great, glad we found the cause
