### ISSUE TITLE
Ch11, Callbacks section: a few small items

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#392]
1. In this sentence: 

"The third argument given to the handler, done, is a callback function that it must call when it is done with the request."

The "done" argument is the fourth argument. 

2. Since the above sentence refers to two functions, the handler and the callback, the next sentence would be more immediately clear if the function being referred to was specified, like this:

"If we had used the **handler** function’s return value as the response value, that would mean that a request handler can’t itself perform asynchronous actions."

3. There was a missed opportunity to refer to crow callbacks as "cawbacks" (sorry if you've heard that a million times already :)

**Comment by marijnh** [comment]
Attached patch should help.

**Comment by dhollinden** [comment]
I'm still seeing, "The **third** argument given to the handler...

in the browser, instead of

"The **fourth** argument given to the handler...
