### ISSUE TITLE
Any reason why Alice can't go to Town Hall?

### ISSUE THREAD

**Issue by kapreski** [marijnh/Eloquent-JavaScript#394]
according to the array `roads` Alice can't go directly to Town Hall
is this on purpose? I  just want to be sure in case I have to wire a similar project(or a map or something)  in the future..

![Image of village](https://i.imgur.com/a7bfFST.jpg)

**Comment by marijnh** [comment]
Hi, yes this is on purpose—or at least, I created the graph first, and the artist drew the map from that. I do agree that given the picture, you'd expect a connection there. I'll leave this open and, when I have time, I can check if any of the text has to be updated if we add that edge.

**Comment by marijnh** [comment]
I never got around to this, so I'm going to leave it as it is.
