### ISSUE TITLE
Ch 11, Callback section, possible rewrite about types and handlers

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#397]
I'm re-reading ch 11. The second time through, I realized I had difficulty here, starting with this paragraph:

"Each message is tagged with a _type_, which determines how it is handled. Our code can define handlers for specific request types, and when such a request comes in, the handler is called to produce a response."

The term "handler" is frequently used later on, but it's significance slipped past me in the above. I also didn't understand the distinction between types and handlers because the text states, "Our code can define handlers..." yet the function is named defineRequestType. I wonder if you might consider a re-write similar to this:

"Each message is tagged with a _type_, which determines how it is handled. Our code can define types and associate each one with a _handler_ function. That way, when a specific request type comes in, it's associated handler is called to produce a response."

Then further down, this paragraph:

"The defineRequestType function defines a new type of request. The example adds support for "note" requests, which just sends a note to a given nest. Our implementation calls console.log so that we can verify that the request arrived. Nests have a name property that holds their name."

could be revised like this:

"The defineRequestType function defines a new type of request. The example adds support for "note" requests, which just sends a note to a given nest. The handler for "note" requests calls console.log so that we can verify that the request arrived. Nests have a name property that holds their name."

Thanks

**Comment by marijnh** [comment]
This chapter has been redone entirely in the 4th edition.
