### ISSUE TITLE
Ch 11, Promises section: immediately finishes

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#398]
In this paragraph:

"The easiest way to create a promise is by calling Promise.resolve. This function ensures that the value you give it is wrapped in a promise. If it’s already a promise it is simply returned, and otherwise you get a new promise that immediately finishes with your value as its result."

I'm confused by what's implied by "immediately finishes" here, since further down the text states that a promised value "might appear at some point in the future."

Thanks

**Comment by marijnh** [comment]
Yes, it might, but if you give `Promise.resolve` a plain value it won't, since there's nothing to wait for, which is why it is described this way.
