### ISSUE TITLE
Ch 11, Promises section: handler function

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#399]
In this paragraph:

"But that’s not all the then method does. It returns another promise, which resolves to the value that the handler function returns or, if that returns a promise, waits for that promise and then resolves to its result."

There's not been any mention of handlers in the Promises section yet. Does "the handler function" in the above refer to the callback function registered by the `then` method?

Thanks

**Comment by MaddyGit** [comment]
_then_ method takes two parameters in form of functions _.then( resolve(), reject() )_ Now we assume that the **Promise** was fulfilled and the _resolve()_ function was called and it returned a value say _'resolveValue'_, Now _resolveValue_ would be wrapped in a promise regardless of whatever type it is. Now if _resolveValue_ is a primitive then it becomes the value of it's wrapping **Promise** and if _resolveValue_ is another **Promise** then automatically it's resolution/rejection will be waited and upon resolution/rejection this **Promise's** reject/resolve callbacks would be called accordingly.

**Comment by amine177** [comment]
The handler is the then() itself.

**Comment by amine177** [comment]
The handler is the then() itself in that context.

**Comment by aluminum1** [comment]
I have a slightly different query, which is closely related to the original question by dhollinden. Two paragraphs later, it says:

> To create a promise, you can use Promise as a constructor. It has a somewhat odd interface -
> the constructor expects a function as argument, which it _immediately calls_, passing it a 
>  function that it can use to resolve the promise.

(Italics added)

I don't think this is 100% right, and it confused me for a long time. It seems to me that the constructor to Promise only _partially executes_ the code. It is impossible to fully execute the code, as the two key ingredients (the function to call if the code is successful, and the function to call if the code fails) have not yet been supplied. 

Consider the following code:

```
function myCode(resolve, reject) {
    console.log("Executing my code")
    if (1==1) {
        // The constructor executes up to here
        resolve("Success. Indeed, 1 equals 1.")
    } else {
        // The constructor executes up to here
        reject("Failed. Unfortunately 1 is not quite equal to 1.")
    }
}

let myPromise = new Promise(myCode)
// --> Executing my code
```

When call `let newPromise = new Promise(myCode)`, the constructor runs the code as far as possible, up to the point where it has to call either the resolve or reject functions. It doesn't yet have those, so it can't call them. 

Then, later on, you might say:

```
myPromise.then( message => console.log(message) )
// --> Success. Indeed, 1 equals 1.
```

The .then method supplies the myPromise object with the function which binds to `resolve` in the original constructor. Until you call the .then method, the original code you gave the constructor remains in a kind of limbo, waiting for you give it a function so it can proceed. This is the way I currently understand it, but I may be mistaken.

**Comment by jacekkopecky** [comment]
There's no need to call the `resolve` function a "dummy" one. The purpose of the `resolve` and `reject` functions given to your code is simply to record, whenever that happens, what the promise resolves to, and if any `.then()` callbacks are already set up, to trigger that they will be called, but asynchronously. 

If your code calls `resolve` immediately, the passed value goes in the internal state of the new promise, the same way as if your code called `resolve` later, on timeout or on some event. 

When a promise gets resolved, if it already has some callbacks registered with `.then()`, it will call them, but not immediately – instead it will do that in something called a `microtask` when all other code runs to completion.

This can be shown with a promise that resolves on timeout:

```javascript
console.log('before calling new Promise()');
const p = new Promise((resolve, reject) => {
  console.log('inside new Promise(), before setting timeout');
  setTimeout(() => {
    console.log('in timeout, before calling resolve');
    resolve(42);
    console.log('in timeout, after calling resolve');
  }, 100);
  console.log('inside new Promise(), after setting timeout');
});
console.log('after calling new Promise(), before setting up then()');

p.then(val => {
  console.log('inside then() callback, got value ' + val);
});
console.log('after setting up then() callback');
```

We get output like this:

```
before calling new Promise()
inside new Promise(), before setting timeout
inside new Promise(), after setting timeout
after calling new Promise(), before setting up then()
after setting up then() callback
in timeout, before calling resolve
in timeout, after calling resolve
inside then() callback, got value 42
```

First all top-level code and all code inside the `new Promise()` constructor runs: we set up the timeout and we set up the then callback. Later, the timeout times out and the whole inside of that happens, which calls `resolve()`; and only after all that has finished, the `.then()` callback is called.

If a promise is already resolved when you register a new callback with `.then()`, that callback also gets called in a microtask after your code runs to completion.

Example:

```javascript
console.log('before calling new Promise()');
const p = new Promise((resolve, reject) => {
  console.log('inside new Promise(), before calling resolve()');
  resolve(42);
  console.log('inside new Promise(), after calling resolve()');
});
console.log('after calling new Promise(), before setting up then()');

p.then(val => {
  console.log('inside then() callback, got value ' + val);
});
console.log('after setting up then() callback');
```

This gives the following output:

```
before calling new Promise()
inside new Promise(), before calling resolve()
inside new Promise(), after calling resolve()
after calling new Promise(), before setting up then()
after setting up then() callback
inside then() callback, got value 42
```

The last two lines show that the `.then()` callback gets called later, after the code that sets up that callback runs to completion.

Hope this helps; promises are really complicated.

**Comment by jacekkopecky** [comment]
To add, of course you can have multiple callbacks set up with `.then()`:

```javascript
console.log('before calling new Promise()');
const p = new Promise((resolve, reject) => {
  console.log('inside new Promise(), before calling resolve()');
  resolve(42);
  console.log('inside new Promise(), after calling resolve()');
});
console.log('after calling new Promise(), before setting up then() callbacks');

p.then(val => {
  console.log('inside then() callback, got value ' + val);
});
p.then(val => {
  console.log('inside second then() callback, got value ' + val);
});
console.log('after setting up both then() callbacks');
```

Which outputs 

```
console.log('before calling new Promise()');
const p = new Promise((resolve, reject) => {
  console.log('inside new Promise(), before calling resolve()');
  resolve(42);
  console.log('inside new Promise(), after calling resolve()');
});
console.log('after calling new Promise(), before setting up then() callbacks');

p.then(val => {
  console.log('inside then() callback, got value ' + val);
});
p.then(val => {
  console.log('inside second then() callback, got value ' + val);
});
console.log('after setting up both then() callbacks');
```

Try the same with the timeout example.

**Comment by aluminum1** [comment]
This does help - thanks. But I would like a bit more explanation for why you say that the engine does not make a "dummy resolve function" when the constructor of the Promise is first called. 

Consider your second example:

``` javascript
console.log('before calling new Promise()');
const p = new Promise((resolve, reject) => {
  console.log('inside new Promise(), before calling resolve()');
  resolve(42);
  console.log('inside new Promise(), after calling resolve()');
});
console.log('after calling new Promise(), before setting up then()');

p.then(val => {
  console.log('inside then() callback, got value ' + val);
});
console.log('after setting up then() callback');
```
If you run the Chrome debugger on this example, and step line by line through the code, a "miracle" occurs. The debugger merrily executes the line

``` javascript 
resolve(42)  // <--- it executes this, no problem
```

with absolutely no qualms, and simply continues to the next line.

How can that be, when the resolve function has not yet been defined? 

In normal execution, trying to execute a function which has not been defined yet would throw an error. 

I don't see that you directly answered this question. The only answer I can suggest is my original one. Namely, that when the Chrome V8 engine encounters the line

``` javascript 
resolve(42)  
```

it stores on the internal state of the promise (which we can't see) some memo to itself which says: "the resolve function was called with the value 42". 

Then, much later in your code, when you finally define the resolve function via the then() method, eg. 

``` javascript
p.then(f);
```

the V8 engine will now call `f` with the argument that it recorded in the memo it wrote to itself earlier (42). This is the only way I can explain what is going on!

**Comment by jacekkopecky** [comment]
Ah, I think I see. When we say `p.then(f)`, I wouldn't say `f` is the resolve function, rather a _callback_ for when `p` resolves, or equivalently a function that should be called once with the value of `p`.

It is an interesting angle to see `resolve(value)` as calling any (even future) `.then()` callbacks, but I don't think it matches my understanding of program flow most of the time.

Consider this code:

```javascript
let x=42;
//… some more code
f(x);
```

I wouldn't think of the line `let x=42` as calling function `f`; in this way, `resolve(42)` to me feels more like storing a value than like calling further code.

**Comment by aluminum1** [comment]
Ok - but that means you are agreeing with me. We are in agreement that when the browser engine (eg V8) executes the code

``` javascript
resolve(42)  // <-- it executes this happily, before resolve is defined
```

it is storing a value for later use. In other words, before the real `resolve` function is provided some time later (by calling the `.this` method), the V8 engine is using a dummy version of resolve. This dummy version has the following pseudocode definition

``` javascript
function resolve(value) {
   Store a log of value on the stack. The real resolve function will one day execute it.
}
```

**Comment by jacekkopecky** [comment]
Hi, thanks for continuing this – it's very interesting to try to come to the source of our different understanding.

In the above, we agree on what happens, but not on how things should be named. I still don't think that there is a dummy and real resolve. It would be like describing this:
```javascript
let x=42;
//… some more code
f(x);
```
as using a dummy function `dummyF` before the code provides a real function (here `f`) by calling something with `x` as a parameter.

To me, `resolve()` is always real, calling `.then()` does not provide a _real_ resolve. `resolve()` is like the assignment operator, not like a calling a function.

Maybe this might be a good example:

```javascript
const p = new Promise(…); // create a promise like we've done above
p.then(f);
p.then(g);
p.then(h);
```

All of `f`, `g`, and `h` will be called when p has a value. Would you call all of them the real resolve?

**Comment by aluminum1** [comment]
Hi Jack - yes, let's keep going. Thank you for continuing civilly.

Let's backtrack a bit. I want to make sure we are on the same starting page. I'm not sure you understand just how strange promises are. Let me return to the code you wrote. I have removed the .this call as I think it confuses the issue.

``` javascript
function executor(resolveFunc) {
    console.log('inside executor, before calling resolveFunc');
    resolveFunc(42);
    console.log('inside executor, after calling resolveFunc!');
}

let P = new Promise(executor);
```
Remarkably, this is perfectly acceptable code to the engine, even though we never define the resolveFunc function. What happens when we execute it? It is much more instructive to execute it line by line using a debugger. What happens has to be seen to be believed! Anyway, we get the following output:
```
inside executor, before calling resolveFunc
inside executor, after calling resolveFunc!
```
Do you accept that this is incredibly strange? When the engine executes the line
```
let P = new Promise(executor);
```
it doesn't _just_ call the constructor of the Promise class (which is what you seemed to think it did). That constructor also  _immediately calls_ the executor function! That's what Marijn says in his book, and it is true. It has to be seen to be believed! This means, that the engine merrily executes this code:
```
    console.log('inside executor, before calling resolveFunc');
    resolveFunc(42);  // <---- WOW! It happily calls an undefined function!
    console.log('inside executor, after calling resolveFunc!');
```
_without having a defintion of resolveFunc_!!! If you don't believe me, step through it with the debugger. It executes that line, no problem. I'm not sure you appreciate that. Are we on the same page? Do you agree it is very, very weird? 

The only way to explain what the engine does here is that when the Promise constructor function calls the executor function, it gives it a dummy function of resolveFunc, as I explained above. There is no other way to explain it. 

In fact, I believe my interpretation of what is happening is consistent with what it says on the Mozilla [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). The documentation is a bit confusing, but it says at one point:

>At the time when the constructor generates the new promiseObj, it also generates a >corresponding pair of functions for resolutionFunc and rejectionFunc; these are "tethered" to the >promiseObj.

These "generated" functions are exactly the "dummy" functions I was talking about.

**Comment by marijnh** [comment]
There's really nothing magical about these functions. Does looking at a something like this [simplified promise implementation](https://gist.github.com/unscriptable/814052) help clear things up?

**Comment by marijnh** [comment]
To answer the original question in this issue, which I for some reason hadn't yet, yes, it does refer to that function.

**Comment by aluminum1** [comment]
> Does looking at a something like this [simplified promise implementation](simplified promise implementation) help clear things up?

Thanks for this. I will try to work through it. I've seen other implementations, but they didn't address the issues that were confusing me, but this one seems to do it somehow.
