### ISSUE TITLE
Ch. 7  – Persistent group exercise hint

### ISSUE THREAD

**Issue by mikegowen** [marijnh/Eloquent-JavaScript#401]
Shouldn't this...

> To add a property (empty) to a constructor that is not a method, you have to add it to the constructor after the class definition, as a regular property.

be this...

> To add a property (empty) to a class that is not a method, you have to add it after the constructor in the class definition, as a regular property.

I may be totally misunderstanding. If so, ignore.

**Comment by mikegowen** [comment]
Also, separately. I'm not sure I understand the need for the empty property. Why not just create them normally?

`let newGroup = new PGroup(collection);`

Also, could you do this instead of the way you define the empty property?

```
static get empty() {
  return new PGroup;
}
```

**Comment by marijnh** [comment]
The property is added to the constructor function. Whether that is the same as the "class" is another discussion, but "constructor" is more specific in this case.

> Why not just create them normally?

You could, but that's not the interface the exercise is asking you to implement.
