### ISSUE TITLE
Ch. 9 – Typo

### ISSUE THREAD

**Issue by mikegowen** [marijnh/Eloquent-JavaScript#404]
http://eloquentjavascript.net/09_regexp.html#p_clbD+OAS4y

>Our task is to convert a string like this into an object whose properties hold strings for sectionless settings and sub-objects for settings, with those sub-objects holding the section’s settings.

Should be?

>Our task is to convert a string like this into an object whose properties hold strings for sectionless settings and sub-objects for sections, with those sub-objects holding the section’s settings.

**Comment by marijnh** [comment]
Thanks for spotting that, I've fixed it.
