### ISSUE TITLE
Ch. 20, 'The HTTP module' part.

### ISSUE THREAD

**Issue by Spiralfate** [marijnh/Eloquent-JavaScript#406]
There is a code snippet in making client's request article: 

const {request} = require("http");
let requestStream = http.request({
...

Is it just me, or it should be just:
'let requestStream = request({' 
since we have already extracted 'http.request' function and made it a value of 'request' binding?
Thanks

**Comment by marijnh** [comment]
You're right. Attached patch fixes that.
