### ISSUE TITLE
Ch. 15, window object

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#413]
Hello, 

After studying Ch. 15 I realized that I didn't specifically understand what the window object was. We were adding event listeners to it, though it wasn't actually defined. I've subsequently read about it at MDN. 

Perhaps there'd be a benefit to a 1-2 sentence definition in Ch. 15?

Thanks!

**Comment by marijnh** [comment]
Good idea. See attached patch
