### ISSUE TITLE
Reset sandbox keyboard shortcut not working

### ISSUE THREAD

**Issue by dhollinden** [marijnh/Eloquent-JavaScript#414]
Hello, 

I've noticed that the control-q keyboard shortcut is not resetting the sandbox for me in Chapters 14 and 15. The Reset Sandbox command from the sandbox menu does work as expected. 

OS X 10.13.3
Google Chrome is up to date: Version 65.0.3325.181 (Official Build) (64-bit)

Thanks

**Comment by marijnh** [comment]
Thanks for noticing that. I fixed it in attached patch, and also moved the shortcut to ctrl/cmd-x since ctrl-q is commonly used for closing windows.
