### ISSUE TITLE
Alternative dark theme

### ISSUE THREAD

**Issue by ino76** [marijnh/Eloquent-JavaScript#421]
Hi Marijnh, congratulations on the release of the third edition of the book.
I read the book on a 27" monitor and the big white screen is really agressive,
so allow user to choose dark theme would be nice feature.

Something like here >> [crystal lang - overview](https://crystal-lang.org/docs/overview/) (click on letter 'A' on top, after 'edit this page')

I may try to make it on my fork.

**Comment by usrnull** [comment]
Use [Dark Reader](https://github.com/darkreader/darkreader)
![dark-mode](https://user-images.githubusercontent.com/16057969/41971957-8b421c2e-7a10-11e8-9ceb-33561acca314.png)
