### ISSUE TITLE
French Translation?

### ISSUE THREAD

**Issue by boussarilatif** [marijnh/Eloquent-JavaScript#440]

**Comment by Essential** [comment]
👋🏻 I've started working on the translation: https://github.com/Essential/JavaScript-Eloquent

**Comment by svngoku** [comment]
I've started to translate the book in french , link : https://github.com/svngoku/Eloquent-JavaScript-Fr

**Comment by marijnh** [comment]
Nice! Any chance you could include the source text, rather than just the images and pdf output, in the repository?

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
