### ISSUE TITLE
Ch 5: Code Sandbox "scripts.js" Typo

### ISSUE THREAD

**Issue by nicolelivingston** [marijnh/Eloquent-JavaScript#441]
I believe there is an error in the "scripts.js" file in the Chapter 5 Code Sandbox. It lists the language "Hangul" as "living: false"; however, Hangul is the main alphabet for Korean language and is definitely still in use today.

**Comment by marijnh** [comment]
Thanks for pointing that out! Probably a mistake I made when entering the data. Fixed in patch f0e99b6
