### ISSUE TITLE
Overlapping text on Table of Contents

### ISSUE THREAD

**Issue by gareys** [marijnh/Eloquent-JavaScript#443]
Browser: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
OS: Windows 10
Breakpoint: Desktop (>=1160px)

In the table of contents, the text `(Part 1: Language)` overlaps the `1. Values, Types, and Operators` text.

![overlapping](https://user-images.githubusercontent.com/8252379/40332260-7b7ca356-5d21-11e8-8753-a78e8b7e461e.JPG)

I was able to fix this by updating the `.toc h3` css styles:

```
.toc h3 {
    position: absolute;
    margin: 0;
    top: 1px;
    right: 0;
    font-family: inherit;
    font-weight: normal;
    font-size: 80%;
    line-height: 1.8;
}
```

This is how it looks with the applied styles:

![fixed](https://user-images.githubusercontent.com/8252379/40332347-cdc90d20-5d21-11e8-9012-d14abe215f04.JPG)

**Comment by gareys** [comment]
https://github.com/marijnh/Eloquent-JavaScript/pull/444 should do the trick.

**Comment by marijnh** [comment]
Are you saying your browser window is 1160px wide? For me, at that width, there's plenty room for the part titles. But maybe that's because we have different fonts. Does patch cbd502c help?

**Comment by gareys** [comment]
Patch cbd502c didn't seem to affect the overlapping issues in the table of contents. See below:

Screen resolution is 1680px wide.

Browser: Chrome 66
OS: Mac OS High Sierra 10.13.3

<img width="1680" alt="screen shot 2018-05-22 at 3 52 58 pm" src="https://user-images.githubusercontent.com/8252379/40386721-8595c3ba-5dd8-11e8-9b40-4e849b670fba.png">

**Comment by marijnh** [comment]
> Screen resolution is 1680px wide.

Ahh, the font chosen on your system is way wider than the one I get. *And* I screwed up the flexbox styles so that the TOC doesn't get wider than 500px, so the extra screen space didn't work.

Patch bd97dcd fixes the width and makes the part headers float, so that the browser will wrap text to avoid overlap. Is that better?

**Comment by gareys** [comment]
:clap: So much better.
