### ISSUE TITLE
Ch 20, urlPath function - separator misbehaviour on Windows

### ISSUE THREAD

**Issue by HattyJetty** [marijnh/Eloquent-JavaScript#446]
https://eloquentjavascript.net/20_node.html#c_LMKrGVrGZP
Here on line 10 the expression `!path.startsWith(baseDirectory + "/")` might result in the wrong value, because the separator difference on Windows is not taken into account.

I guess this can be avoided by concatenating with the `sep` from [`path` module](https://nodejs.org/api/path.html#path_path_sep).

**Comment by marijnh** [comment]
Thanks for pointing that out. Attached patch updates the code to use `sep`
