### ISSUE TITLE
Full text search or index chapter?

### ISSUE THREAD

**Issue by crelder** [marijnh/Eloquent-JavaScript#449]
I really love this book and find it very useful. Thank you!

I would like to use this book also as a reference book, where I can quickly find help to certain questions: e.g. json.

Therefore a full text search on the front page would be an improvement from my point of view. Or some kind of index chapter at the end. But I see this just as an additional feature.

I use this [paperback book](https://www.amazon.de/Python-Ge-Packt-Ge-packt-Michael-Weigend/dp/3958457185/ref=sr_1_1?s=books&ie=UTF8&qid=1529936483&sr=1-1&keywords=python+ge-packt) for python, which functions very well as a reference book thanks to an index in the back.

**Comment by marijnh** [comment]
The PDF ebook comes with an index. For the HTML version, I'm not currently planning to add a search feature.

**Comment by crelder** [comment]
Okay. That works for me as a solution, since I am planning on buying the paperback book as soon as it comes out in October.
Thanks Marijnh.
