### ISSUE TITLE
Persian Translation

### ISSUE THREAD

**Issue by mahdavipanah** [marijnh/Eloquent-JavaScript#456]
Hi,
I am interested in translating this incredible book into the Persian language. Since I didn't find any translation guideline or legal terms, I created this issue to ask if there is any legal restrictions for a free and non-profit translation of the book and if there is any documentation for learning more about the build system.

Thanks.

**Comment by marijnh** [comment]
Hi, great to hear from you. As long as you don't use the translation for profit, you should be safe with regards to the license. To build the HTML version of the book, you'll have to install node.js and make, run `npm install` in a clone of this repository, followed by `make`. You may also need to tweak some style sheets, since I assume Persian means right-to-left text. Building the pdf version is... difficult, and you should probably not bother.

Do note that this is a big book—translating it on your own is going to take a lot of time. I recommend doing the work in the open, in a github fork, so that even if you don't get all the way through, others can pick up and help with the work.

**Comment by mahdavipanah** [comment]
My intent for this translation is completely non-profit, so I'll be good to start.

You're right about the right-to-left problem and it'll be not a big problem, I'll tweak the stylesheets to make them right for the Persian language.

I'll fork this project and start translating it in the forked repository so everyone will be welcomed to join.

I have few suggestions that I believe will make the project's structure more contribute friendly:

- Choose a specific license for the project so beside protecting your own rights as the main author and having no concern about the use of your work, others will also be more sure about how and where they can use the content and source.

- Add a __CONTRIBUTING.md__ , __TRANSLATING.md__ and also a list of translation repositories so anyone can see where they can find other people's translation work.

- Add a documentation for the build system, it's very confusing 😅

Sorry if I talked too much, I love this book so much that I want to do whatever I can, to make it even better.

Thanks for your work.

**Comment by mahdavipanah** [comment]
Link to my Persian translation repo: https://github.com/mahdavipanah/Eloquent-JavaScript

**Comment by marijnh** [comment]
> Choose a specific license for the project 

Is the [current license](https://creativecommons.org/licenses/by-nc/3.0/) not specific enough?

**Comment by mahdavipanah** [comment]
> > Choose a specific license for the project
> 
> Is the [current license](https://creativecommons.org/licenses/by-nc/3.0/) not specific enough?

Sorry, you're right. I only looked up the repository for a LICENSE file, but now I just found the complete license description on the [website](http://eloquentjavascript.net/).

**Comment by mahdavipanah** [comment]
In contrast to the English, in the Persian language, we have to separate pronouns for the singular second person and the plural second person.
When it comes to the book's writing tone and the way you want to call the readers, do you prefer to translate "you" as a singular second person or a plural second person?

**Comment by marijnh** [comment]
Definitely singular, yes.

**Comment by marijnh** [comment]
See also https://emehran.github.io/persian-eloquent-javascript/index.html , another Persian translation.

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
