### ISSUE TITLE
Chapter 11 - Message Routing - Needn't catch when connections not defined ?

### ISSUE THREAD

**Issue by MaddyGit** [marijnh/Eloquent-JavaScript#460]
Line mentioned in the comment in _requestType()_ method refers to _connections_ in _nest.state_ which might not be defiend at times, like upon very first call to _everywhere()_ in this section of code:

1. _everywhere()_ defined connections for first Node, say **[Church Tower]** and called _broadcastConnections( **[Church Tower]**, 'Church Tower' )_

2. _broadcastConnections()_ called 
_request( **[Church Tower]**, **[Sportsgrounds]**, 'connections',
       **{ name: 'Church Tower', neighbors: [Array of neighbors of 'Church Tower'] }** )_ 
which called 
**[Church Tower]**_.send( **[Sportsgrounds]**, 'connections', 
**{ name: 'Church Tower', neighbors: [neighbors of 'Church Tower'] }**, resolverCallback )_ 
which in turn reached handler-callback method defined in _requestType()_ with arguments
_( **[Sportsgrounds]**, 
**{ name: 'Church Tower', neighbors: [neighbors of 'Church Tower'] }**, 'Church Tower' )_

3. Now **[Sportsgrounds]** node doesn't yet have _state.connections_ defined as it would be defined in _everywhere()_ method's (nth after first i.e. 2nd or 3rd or . . .) call and by now _everywhere()_ 's first call hasn't returned yet, So the referencing to _nest.state.connections_ (nest is **[Sportsgrounds]**) would throw **TypeError: nest.state.connections is undefined** shouldn't code handle this like by returning/defining when undefined ? 
"Here on my machine I was able to produce this error after plucking out _setTimeout()_ s from the _send()_ method."

```
requestType("connections", (nest, {name, neighbors},
                            source) => {
//Following is the line of code with issue
  let connections = nest.state.connections;
  if (JSON.stringify(connections.get(name)) ==
      JSON.stringify(neighbors)) return;
  connections.set(name, neighbors);
  broadcastConnections(nest, name, source);
});

function broadcastConnections(nest, name, exceptFor = null) {
  for (let neighbor of nest.neighbors) {
    if (neighbor == exceptFor) continue;
    request(nest, neighbor, "connections", {
      name,
      neighbors: nest.state.connections.get(name)
    });
  }
}

everywhere(nest => {
  nest.state.connections = new Map;
  nest.state.connections.set(nest.name, nest.neighbors);
  broadcastConnections(nest, nest.name);
});
```
[Reference to the Code](http://eloquentjavascript.net/11_async.html#c_68Z9trrpeS)

**Comment by marijnh** [comment]
Hi. Since sending messages between nodes is asynchronous, and `everywhere` runs synchronously on every nest, all nodes will have a value in `state.connections` when they start receiving `"connections"` messages. I agree this is a bit subtle, and the way `everywhere` works isn't obvious, but I don't think there's a bug in the current code.

**Comment by MaddyGit** [comment]
you're right, I didn't mean a bug, I was just worried about depending upon setTimeout as I hear it's not precise, still I'm new to JavaScript so you know better + can't thank you enough ever for compiling this book!
