### ISSUE TITLE
Link to 3rd edition not working

### ISSUE THREAD

**Issue by RajSunner** [marijnh/Eloquent-JavaScript#461]
Hi, the 'available' link to the 3rd edition on the homepage shows an Amazon 'page not found' message.

Note that it does work correctly when the href is copied directly into the address bar, just not via clicking the link.

**Comment by marijnh** [comment]
Ughh. Seems Amazon has implemented some kind of blocking features for the international link service I'm using (so that people get redirected to a local store when possible). Thanks for reporting that. I'll see if I can find a workaround.

**Comment by marijnh** [comment]
Ah, right, I screwed up the link. Weird that it works when pasted but not when followed directly! But should be fixed now.

**Comment by RajSunner** [comment]
Thanks.  I can confirm it's now fixed.
