### ISSUE TITLE
Correction on floating point representation

### ISSUE THREAD

**Issue by erimcg** [marijnh/Eloquent-JavaScript#463]
In the section on values in chapter 1, when first discussing floating point numbers you state "To do this, some of the bits are used to store the position of the decimal point." The position of the decimal point is not stored.  Floating point numbers are represented according to the IEEE 754 standard which stores a sign, mantissa, and exponent.

**Comment by marijnh** [comment]
Well, it's technically a _binary_ point, but that is pretty much what the exponent is—the position of the point. And since point notation is referred to as 'decimal point' in English, I think my description is correct enough without getting into too much detail.
