### ISSUE TITLE
Can't upload epub file to Google Play Books

### ISSUE THREAD

**Issue by jkevingutierrez** [marijnh/Eloquent-JavaScript#470]
Hi,

Awesome book! I'm just trying to upload it to Google Play Books but I cannot upload it. I tried to run this validator: http://validator.idpf.org/application/validate and I got the next Fatal error: 
`
Type | File | Line | Position | Message
-- | -- | -- | -- | --
FATAL | frontmatter.xhtml | 44 | 62 | Fatal Error while parsing file 'The reference to entity "asin-com" must end with the ';' delimiter.'.

`

**Comment by marijnh** [comment]
Ah, I recently broke that it seems—epub uses xhtml, which is way stricter about all kinds of things than html. Attached patch should help.
