### ISSUE TITLE
Suggested writeFile for exercise 21.1 returns "Error: Internal Server Error"

### ISSUE THREAD

**Issue by alexandersandberg** [marijnh/Eloquent-JavaScript#478]
The [solution for exercise 21.1](https://eloquentjavascript.net/code/#21.1), suggesting using `writeFile` in the update function, gives me an alert with "Error: Internal Server Error", and the JSON is not written to the file.

Not sure if I'm doing something wrong with `writeFile`, but I managed to solve the problem by using the synchronous `writeFileSync` instead.

**Comment by marijnh** [comment]
Ah, right, newer versions of node have started requiring a 3rd argument to `writeFile`. I've updated the solution to pass one in attached patch.
