### ISSUE TITLE
Chapter 21 Skillsharing comments don't work in Safari

### ISSUE THREAD

**Issue by jefflovejapan** [marijnh/Eloquent-JavaScript#480]
I've tried running the skillsharing sample code for Chapter 21 (as well as working through it in the book) and it seems that the comment paragraphs are resolving to a `display` value of `none`, hiding them from the page in Safari 12.1. The issue does not appear in Chrome.

I've tried manually editing `skillsharing.css` to add `display: block` but it doesn't seem to make a difference. I'm new to HTML and CSS so can't figure out why it would work in Chrome and not Safari.

<img width="1552" alt="Screen Shot 2019-05-20 at 10 19 24 PM" src="https://user-images.githubusercontent.com/3140681/58061664-85437680-7b4d-11e9-807d-002193b4f0fa.png">

**Comment by karbassi** [comment]
@jefflovejapan it looks like you may have a Safari extension/addon that has added a `display: none;` to the `comment` class. 

Notice that "user stylesheet".

<img width="300" alt="58061664-85437680-7b4d-11e9-807d-002193b4f0fa" src="https://user-images.githubusercontent.com/17738/58126065-af417b00-7bd7-11e9-92ec-67bb494ae86c.png">


Disable all extensions and try it again.

**Comment by jefflovejapan** [comment]
That's totally the problem. Thanks for the help.
