### ISSUE TITLE
Ch. 11 sandbox syntax error

### ISSUE THREAD

**Issue by leucotic** [marijnh/Eloquent-JavaScript#484]
The sandbox (including with the solution) both give  "SyntaxError: Unexpected token function" when you try to run them

**Comment by leucotic** [comment]
(for the first question - scalpel)

**Comment by marijnh** [comment]
What browser (and version) are you using?

**Comment by leucotic** [comment]
Yeah I was thinking that might be the problem. I'm on an old windows 7, I don't think the browser (chrome) has been updated since 2014. (my normal comp is getting parts replaced so I'm using this one temporarily). Just tried it on my phone and it does seem to be working, so this is probably an issue on my end. my bad.
