### ISSUE TITLE
Ch. 15 - throttle function

### ISSUE THREAD

**Issue by itainoam** [marijnh/Eloquent-JavaScript#490]
In the chapter you have a throttling implementation:

```
  let scheduled = null;
  window.addEventListener("mousemove", event => {
    if (!scheduled) {
      setTimeout(() => {
        document.body.textContent =
         `Mouse at ${scheduled.pageX}, ${scheduled.pageY}`;
        scheduled = null;
      }, 250);
    }
    scheduled = event;
  });
```

The downside with this implementation is that it introduce delay. The function is alway fired with event that is 250ms old.

Wouldn't is be better to have something (generalized example) along the lines of:
```
function throttle(func, delay) {
  let isRunning;
  return function(...args) {
    let context = this;  
    if (!isRunning) {
      isRunning = true;
      func.apply(context, args);
      setTimeout(function() {
        isRunning = false;
      }, delay);
    }
  }
}
```

If you think that's helpful I can open a pull request with a suggested change.

**Comment by marijnh** [comment]
That'll ignore the last bunch of events if they don't happen to end exactly on a new time slice, which is usually a lot worse than a delay. There's a hundred ways to do debouncing, I'm showing a simple one, I think the code is fine as it is.
