### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by lkreimann** [marijnh/Eloquent-JavaScript#496]
I'd like to translate this book to german. It might take a while when I'm going to work alone on this, but maybe there's somebody (or multiple people) who would like to work on this together with me. 

I haven't found another german translation yet (or a WIP for that matter). If someone knows anything, please point me to the repo. Hints are very much appreciated!

**Comment by marijnh** [comment]
Wonderful. I haven't heard from anyone working on a German translation of the 3rd edition, so I guess you can start from a fresh fork (do link to it here).

**Comment by lkreimann** [comment]
Alright, I'm gonna work on it here: https://github.com/lkreimann/Eloquent-JavaScript

I'm thankful for all the help I can get!

**Comment by mrunkel** [comment]
Hey @lkreimann, I'd be willing to help out, I don't see much progress on your fork. Is it offline somewhere, is there anywhere in particular you'd like me to start?

**Comment by lkreimann** [comment]
Hi @mrunkel, my progress here equals zero on my fork :( feel free to make a new fork and I'd be happy to help out on it! I don't have much time right know (or sitting in front of an IDE isn't that much of a priority in my life right now), so I'm not sure if I'm the best to shoulder such a big project :D Would love to help though

**Comment by leichteckig** [comment]
Hello @mrunkel 
did you already start / did some progress?
I'd love to help out as well. 🙂 How can I do that best?

**Comment by mrunkel** [comment]
Hi @leichteckig . I haven't started. But your comment has spurred me to action. :) 

I've now forked the repo [here](https://github.com/mrunkel/Eloquent-JavaScript) and invited you as a collaborator.  You can check it out and make changes and then just push them back.  I'll go ahead and make issues for each chapter, then when you want to work on a chapter, just assign the issue to yourself.

**Comment by leichteckig** [comment]
Thank you, that sounds perfect! ❤️ I'll start right away, looking forward to being helpful. 🙂

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
