### ISSUE TITLE
Chapter 11 - Why try/catch is needed in the requestType function?

### ISSUE THREAD

**Issue by alexpi** [marijnh/Eloquent-JavaScript#499]
In the requestType function we have:
```js
function requestType(name, handler) {
  defineRequestType(name, (nest, content, source, callback) => {
    try {
      Promise.resolve(handler(nest, content, source))
        .then(response => callback(null, response),
              failure => callback(failure));
    } catch (exception) {
      callback(exception);
    }
  });
}
```
The text states that the call to handler had to be wrapped in a try block to make sure any exception it raises directly is given to the callback.

Since Promise.resolve converts the value returned by handler to a Promise, shouldn't the second argument to then() catch all exceptions?

**Comment by marijnh** [comment]
The call to `handler()` happens in the function itself, so when that throws, it'll raise a regular exception rather than creating a rejected promise.
