### ISSUE TITLE
Chapter 15 Scroll Event

### ISSUE THREAD

**Issue by hkiame** [marijnh/Eloquent-JavaScript#501]
document.body.appendChild(document.createTextNode("supercalifragilisticexpialidocious ".repeat(1000))); affects the width of the body and not the height. The scroll event thus not fired.

**Comment by marijnh** [comment]
Unless you remove the space at the end, it does line-wrap and affect the height. At least, that example works fine for me.

**Comment by hkiame** [comment]
ooh yeah. i missed the space. Thanks
