### ISSUE TITLE
Ch14 - exercise - build a table

### ISSUE THREAD

**Issue by jasontwuk** [marijnh/Eloquent-JavaScript#502]
The hint for this exercise suggests us to use **document.createTextNode** to create text nodes.
https://eloquentjavascript.net/14_dom.html#p_2Q6e2rAy5t
But the solution for this exercise is using **Node.textContent** to add text content to the nodes. 
https://eloquentjavascript.net/code/#14.1
I understand both methods work, but I think it might be nicer if the hint and solution are using the same method. Thank you.

**Comment by marijnh** [comment]
Thanks for noticing that. Attached patch adjusts the solution.
