### ISSUE TITLE
Ch:21 localStorage is not defined

### ISSUE THREAD

**Issue by JulioDavidCh** [marijnh/Eloquent-JavaScript#503]
I get the error when trying to run the skillsharing_client.js file with node, i got node v12.13.0 installed and also installed the esctatic package. I downloaded the files of the project here https://eloquentjavascript.net/code/skillsharing.zip and this is the error i get when running it: https://imgur.com/NkT8H1A

**Comment by marijnh** [comment]
`localStorage` is a browser thing—you appear to be running a script meant for the browser in node. To start the server, start `skillsharing_server.js` with node.

**Comment by zzehli** [comment]
Just to add some further instructions: first run the server with `node skillsharing_server.js`, then open the browser and type `localhost:8000` and you will see the website. No need to open the `public` folder.
