### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by alikahwaji** [marijnh/Eloquent-JavaScript#505]
Hi,

I would like to translate the latest edition to arabic, I tried to find an arabic version but couldn't find one so it will a good opportunity to do that.

Cheers

Ali

**Comment by marijnh** [comment]
That'd be wonderful. Make sure you're read my [notes](https://github.com/marijnh/Eloquent-JavaScript#translating) for translators.

**Comment by alikahwaji** [comment]
Awesome, thanks for notes :)

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
