### ISSUE TITLE
Ch11. "timeout arriving after the request finishes" clarification

### ISSUE THREAD

**Issue by alexpi** [marijnh/Eloquent-JavaScript#510]
In 'Networks are hard', after the first code example, the text reads "The first time resolve or reject is called determines the outcome of the promise, and any further calls, such as the timeout arriving after the request finishes [...]".

The "timeout arriving after the request finishes" is ignored because it contains the `if (done) return;`, not because the promise is resolved or rejected, am I correct?

**Comment by marijnh** [comment]
Ah, good point, that paragraph was written before the code had the `done` variable added. Attached patch removes the reference to the timeout.
