### ISSUE TITLE
Chapter 11 code example attempt call should start with parameter '0' instead of '1'

### ISSUE THREAD

**Issue by pstarliu** [marijnh/Eloquent-JavaScript#511]
In the code example in section '**Networks are hard**'

Otherwise if called with `attempt(1)`, it will reject the promise on the third attempt instead of fourth, and will give up after 750 ms instead of after a second, both contradict with the text following the code example.

**Comment by marijnh** [comment]
Ah, thanks for spotting that. Attached patch fixes the inconsistency.

**Comment by pstarliu** [comment]
And I enjoy read your books by the way, I've read the first edition and now halfway on the second edition.
