### ISSUE TITLE
Bugs and Errors - Chapter 8

### ISSUE THREAD

**Issue by qz3f2** [marijnh/Eloquent-JavaScript#512]
The problem I wish to report is contained within the following code, which is somewhere about halfway down the page. 

`function promptNumber(question) {
  let result = Number(prompt(question));
  if (Number.isNaN(result)) return null;
  else return result;
}`

`Number.isNaN("anyString")` returns false, which defeats the purpose of this line.  

The only way this works is to do something along the lines of 
`if(typeof result != 'number') {
  return null
  } else {
  return result; 
}`

**Comment by marijnh** [comment]
> Number.isNaN("anyString") returns false, which defeats the purpose of this line.

Because `result` holds the return value from `Number`, the value passed to `Number.isNaN` will never be a string.
