### ISSUE TITLE
How to run exercise code inside VS Code 

### ISSUE THREAD

**Issue by pstarliu** [marijnh/Eloquent-JavaScript#513]
So that I can get more detailed debug information and might be put a break point if I need, currently the error/debug message I got from the browser is minimal.

For example, I want have an chapter11Exercise1.js file for code for that exercise only. But then for that exercise to run, I need copy/import a few variables or functions from 11-async.js. Or I might as well copy all the content from 11-async.js. 

Is there any better ways to achieve what I want: run exercise inside locally inside any IDE and keep exercise code separate from the code from the book code sandbox?

Thanks

**Comment by marijnh** [comment]
Assuming VS Code uses node to run/debug the code, you could add a line like this to the top of your exercise file:

```
eval(require("fs").readFileSync("/path/to/11_async.js"))
```

That's a bit crude, but it should work. If you can control the way node is launched, you can also do something like ...

```
node -i -e "$(< 11_async.js)"
```
```

**Comment by pstarliu** [comment]
Thanks Marijn, the first solution works., I have to use 
`require("fs").readFileSync(".\\Code\\11_async.js", "utf8")` 
without using the encoding, the readFileSync will return a buffer instead.

I tried to use the second option, but never can get it work, can't even get the simplest scenario work, for example trying to get a simple js file work.
```
  /* hello.js */
console.log('hello');
```
Then I tried either 
`node -i -e "$(< hello.js)"`
or
`node  -e "require('fs').readFileSync('hello.js', 'utf8')"`
they both not working. The first one throw an error like this:

> SyntaxError: Unexpected token <
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Object.<anonymous> ([eval]-wrapper:6:22)
>     at Module._compile (module.js:652:30)
>     at evalScript (bootstrap_node.js:466:27)
>     at startup (bootstrap_node.js:221:13)
>     at bootstrap_node.js:612:3
The second didn't complain, just return an empty line.

I didn't use the `-i`, option yet, think it's probably required for the evaluation result to stay in the current Node execution context so that the my exercise code can be executed later and can re-used the evaluated code. But instead starting from the simplest case to trying things out, and don't know why it doesn't work So not sure the second approach going to work at all?

**Comment by pstarliu** [comment]
Ok, now I am using power shell inside VS code, which has `Get-Content` is the equivalent for unix 'cat', and one of its aliases is 'cat'. 
It is a much better shell than the windows CMD, make the simple case `node -e "$(cat hello.js)"` working. But still failed when I want run the code for chapter 11 exercise using `node --eval "$(cat .\11_asyncv2.js, .\Char11Exercise1.js -Encoding UTF8)"`, something to do with the code has double quote but `$(cat .\11_asyncv2.js, .\Char11Exercise1.js -Encoding UTF8)` need to be wrapped inside double quote.

So I end up using a build task to combine js files before run the code inside node, bit overkill, but once setup, I should be able to reuse the same build and launch setup for all the other exercises without modify the code.

```
// tasks.json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "combine JS files",
            "type": "shell",
            "command": "sc (cat ${workspaceFolder}\\Code\\11_asyncv2.js, .\\Code\\Char11Exercise1.js -Encoding UTF8) -Path ${workspaceFolder}\\Code\\app.js",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```


```
// launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "preLaunchTask": "combine JS files",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "console": "internalConsole",
            "program": "${workspaceFolder}\\Code\\app.js"
        }
    ],
}
```

Guess that's will do for now.
