### ISSUE TITLE
good to use [^] to overcome the dotall problem -- I think [.\n] is equally good

### ISSUE THREAD

**Issue by KennethKinLum** [marijnh/Eloquent-JavaScript#514]
(in p.155 of your book, on the topic Greed, of RegExp)

I think the dotall problem is related to the missing `s` flag such as in Firefox.

Now we can use `[^]` and that's nice way.  I also read that `[\s\S]` (or any pair such as `[\w\W]`) can also work.

Now I think `[.\n]` is also good and worth a mentioning because it gives a clear indication of what wants to be matched, than any other forms out there.

**Comment by marijnh** [comment]
Given that `/[.\n]/.test("x")` returns false, I suspect this doesn't do what you think it does. `/(.|\n)/` would work. But I don't think it's worthwhile to add noise to the text with different suggestions when `[^]` does its job just fine.

**Comment by KennethKinLum** [comment]
ah... i forgot the `.` in the `[]` has special meaning... oops... is there a way to make `.` mean the same thing even inside the `[]`?

**Comment by marijnh** [comment]
I don't think there is

**Comment by KennethKinLum** [comment]
ok, then it can be
`(.|\n)` but I guess it maybe a bit verbose than `[^]` or `[\s\S]` but I think if using `[^]` or `[\s\S]` there may need to be a comment to explain what it does
