### ISSUE TITLE
Chapter 13, TCP explanation

### ISSUE THREAD

**Issue by alexpi** [marijnh/Eloquent-JavaScript#516]
The text reads: 
> For example, when we want to send an email using the SMTP protocol, the machine through which we send it is expected to be listening on port 25.

I have no idea about TCP, but shouldn't the email receiving machine be listening on port 25, instead of the machine sending it?

**Comment by marijnh** [comment]
Email is sent _through_ an SMTP server that takes care of delivering it to the proper destination server. An email client will connect to such a server (on port 25, traditionally), which is what this sentence is talking about.
