### ISSUE TITLE
Chinese (simplified) translation

### ISSUE THREAD

**Issue by yukie1412** [marijnh/Eloquent-JavaScript#518]
We'd  (@sunniejs & I) like to translate this book into Chinese (simplified writing, mandarin)

the forked issue can be found here: https://github.com/sunniejs/Eloquent-JavaScript

**Comment by marijnh** [comment]
Very nice! Good luck. If you want me to call for collaborators on twitter (or retweet something to that effect), let me know.

**Comment by Zheng7426** [comment]
@yukie1412 Hello, I would like to contribute to the translation. If there are still any needs please let me know. Thanks.

**Comment by yukie1412** [comment]
@Zheng7426 welcome! frankly i haven't done much after chap 8. so you can either start with chap 9, or check over the languages in the earlier chapters.

**Comment by Zheng7426** [comment]
@yukie1412 
Understood. Thanks for the info. I will start with chapter 9 then.

**Comment by Zheng7426** [comment]
Hi @yuki1412, sorry to bother you. Can you kindly ask your friend (sunniejs) to check my pull request on her repository? So that if translations for Chapter 9 is acceptable she can merge the pull request. Thanks.

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.

**Comment by Zheng7426** [comment]
@marijnh Ok sir, thank you for letting us know.
@yukie1412 Hi Yukie, are you interested to starting a new issue for the fourth edition?
