### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by osmanizbat** [marijnh/Eloquent-JavaScript#520]
Hi,

I'd like to translate the book to Turkish if i manage to complete.
Any help will be appreciated. 

https://github.com/osmanizbat/eloquent-javascript-turkish-translation

Thanks.

**Comment by marijnh** [comment]
Nice! Good luck. Do you want me to ask on twitter if people want to contribute, or do you prefer to work on your own?

**Comment by osmanizbat** [comment]
Thank you Marjin.  I hope I can handle it myself.

**Comment by ARS-coding** [comment]
Hi @osmanizbat, were you able to finish the translation? If you need someone to assist you I would gladly help!

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.

**Comment by osmanizbat** [comment]
Hi,
@ARS-coding,  unfortunately due to a lack of time and a bit of perfectionism, I was unable to make progress. It would be a great work if you could start over and translate the 4th edition.

Dear @marijnh , i really appreciate your valuable work and dedication. I wish you all the best.

**Comment by ARS-coding** [comment]
I promise I’ll be finishing this work! 
It might take more then I initially anticipated because there’s really a lot of text and I’m currently really trying hard to find a job but my current realistic estimate now would be to finish it in one more month.

Thank you for letting us know.

Warm regards,
Riza.
