### ISSUE TITLE
Indonesian translation

### ISSUE THREAD

**Issue by hanief** [marijnh/Eloquent-JavaScript#521]
Hi,

I intend to translate this book to Indonesian. The fork is here: https://github.com/hanief/Eloquent-JavaScript

Thanks.

**Comment by marijnh** [comment]
Wonderful! Good luck.

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
