### ISSUE TITLE
Russian translation 2nd_edition

### ISSUE THREAD

**Issue by dluschan** [marijnh/Eloquent-JavaScript#523]
Компилирую русский перевод второго издания на основе постов и перевода Вячеслава Голованова http://habrahabr.ru/post/240219/
I am compiling a Russian translation of the second edition based on the posts and translation by Vyacheslav Golovanov http://habrahabr.ru/post/240219/

**Comment by marijnh** [comment]
There used to be a complete Russian translation of the 2nd edition at https://karmazzin.gitbooks.io/eloquentjavascript_ru/content/ . But right now gitbooks.io seems to be entirely down. Not sure how long that has been the case.

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
