### ISSUE TITLE
Chapter 11: how to run routeRequest() after all nodes received connections ?

### ISSUE THREAD

**Issue by thelong0705** [marijnh/Eloquent-JavaScript#525]
Hi, thank you for the great book! 
I'm having trouble running the sample code for Chapter 11.

When ever i tried to run `routeRequest(bigOak, "Church Tower", "note", "Incoming jackdaws!")` command it gives me `Error: No route to Church Tower` because the connections in bigOak haven't got updated. 

Can u tell me how to run the `routeRequest(bigOak, "Church Tower", "note", "Incoming jackdaws!")` command right after the connections has been broadcasted to all nest ?

**Comment by marijnh** [comment]
There's no great way to do this, but you can use `setTimeout` to wait a while before your code runs.

**Comment by thelong0705** [comment]
Thanks for your answer, i was trying to find a way to run it right after the connections has been broadcasted but i guess i will settle for `setTimeout`.
