### ISSUE TITLE
there's String.prototype.padStart() in ES2017

### ISSUE THREAD

**Issue by rosald** [marijnh/Eloquent-JavaScript#528]
in chapter 'Functions' section 'Growing functions'  , we created a function 'printZeroPaddedWithLabel' which add pad '0' to the string.
In fact , since ES2017(which the book 3rd edithon use) , there's String.prototype.padStart() and String.prototype.padEnd() who helps pad the string .
How about add these related contents to the page footer to make it clear

**Comment by rosald** [comment]
i see String.prototype.padStart() , in next chapter 'Data Structures: Objects and Arrays' section 'Strings and their properties' ....

**Comment by marijnh** [comment]
Indeed, it is mentioned later, when methods are introduced.
