### ISSUE TITLE
Ch. 14 - Possible to loop over a NodeList via for/of

### ISSUE THREAD

**Issue by SimonAltrogge** [marijnh/Eloquent-JavaScript#529]
In chapter 14 you mention [here](https://eloquentjavascript.net/14_dom.html#p_H+Wc+lYGt9) that it is not possible to loop over a Node‘s `childNodes` property using a `for/of` loop, since it is not a real array but a `NodeList`.

While it is true, that a `NodeList` is not an array, it is still iterable and therefore possible to be looped over via `for/of` according to the NodeList API on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Example).

If that was not already the case for the 2017 version of JS, excuse my comment on that matter.

Best regards and thanks a lot for your magnificent book!

**Comment by marijnh** [comment]
Good point—I wasn't aware of that. The DOM spec is separate from the JavaScript spec, so ES2017 says nothing about this, but it does look like this has been widely supported since 2016. Attached patch removes the paragraph.
