### ISSUE TITLE
Urdu Translation

### ISSUE THREAD

**Issue by mahboob-awan** [marijnh/Eloquent-JavaScript#536]
Thanks @marijnh for writing an open-source book and for this opportunity to translate it 👍

I will start via the repository: https://github.com/mahboob-awan/Eloquent-JavaScript-Urdu

I will share a hosted link after finishing few chapters.

**Comment by marijnh** [comment]
Wonderful! Good luck.

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
