### ISSUE TITLE
function elt

### ISSUE THREAD

**Issue by hkiame** [marijnh/Eloquent-JavaScript#537]
Instead of having an if else statement you could use an append function which accepts Node objects and DOMStrings. append function takes multiple items instead of having the loop you could use the spread operator.

**Comment by marijnh** [comment]
Sure, you could do that. But I didn't do it that way, which is also fine.

**Comment by hkiame** [comment]
You had talked about the not wanting to use the verbose DOM methods so i thought reducing the amount of code in elt function will make it less verbose by using append method. Thanks for the amazing book!
