### ISSUE TITLE
null.length error is different than the book

### ISSUE THREAD

**Issue by gumbol** [marijnh/Eloquent-JavaScript#542]
hi not an issue. but in VS code i get TypeError: Cannot read property 'length' of null. in the book (p. 60) it say TypeError: null has no properties. 

The VS code description doesnt tell you if the property exist. but from the description it assumes there is one. i used code runner ext.

**Comment by marijnh** [comment]
Right, the precise phrasing of errors depends on the JavaScript engine you're using. The error in the book is the one Firefox emits. I expect VS Code extension uses V8, the engine from Chrome, which has a different message.
