### ISSUE TITLE
[Code page](https://eloquentjavascript.net/code) Show the exercise statement when selecting an exercise from the drop down

### ISSUE THREAD

**Issue by gpskalra** [marijnh/Eloquent-JavaScript#543]
Wouldn't it be better to show the exercise statement (and the display hints option too) when a user selects an exercise from the drop down on this page (https://eloquentjavascript.net/code)? A user can then go about solving exercises without having to go to another tab/window or to the paper book to see the exercise statement and can do it all in one place.

**Comment by gpskalra** [comment]
Oh! I did not realize I can run my code write in the book where the exercise statement exists and do not have to work in the code sandbox. This would still be a nice addition to the code sandbox though.

**Comment by marijnh** [comment]
No, duplicating that text there feels messy. As you found, people using the online text can work on exercises right in the text.
