### ISSUE TITLE
deepcompare and code share

### ISSUE THREAD

**Issue by gumbol** [marijnh/Eloquent-JavaScript#544]
hi 
for the deepcompare exercise chapter4.
It is not clear for me if you need to take into consideration a case where both objects have same properties and values but different order.

just to be clear we are comparing two objects properties and order doesnt change their value compared to string or number

Also i would suggest creating a space where everyone can share there solutions.

**Comment by marijnh** [comment]
The idea is to not take order into consideration.

Setting up or moderating any kind of interactive spaces around this book is not something I'm currently willing to put time and energy into, sorry.

**Comment by gumbol** [comment]
what i meant is maybe a markdown page here on github where someone can edit with their code.
