### ISSUE TITLE
array parameter require parentheses

### ISSUE THREAD

**Issue by gumbol** [marijnh/Eloquent-JavaScript#545]
following the ch3 arrow functions definition explanation.

this function definition throws a malformed arrow function error.
arr = [ele] => ele >1;

this however works
arr = ([ele]) => ele > 1;

it seems that arrays are not treated as a single parameter.

**Comment by marijnh** [comment]
Only plain parameters allow you to omit the parentheses for a single parameter. When destructuring or adding a default value, you always have to include them.

**Comment by gumbol** [comment]
awesome thanks!
