### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by gumbol** [marijnh/Eloquent-JavaScript#546]
chapter 6 the beginning of the paragraph just above the Symbols section.

"And **we** can also add this interface to your own objects! But before we can do that, we need to know what symbols are."

replace "and we" with "and you"

**Comment by marijnh** [comment]
Thanks for pointing that out. I think it works better when changing 'your' to 'our', as in attached patch.

**Comment by gumbol** [comment]
That works as well. thank you!
