### ISSUE TITLE
There is no fillColor property of a canvas drawing context

### ISSUE THREAD

**Issue by hkiame** [marijnh/Eloquent-JavaScript#550]
On page 333 it is write hexadecimal digits being used in the fillColor property of canvas drawing context. There is no fillColor property but fillStyle.

**Comment by marijnh** [comment]
That's listed on the [errata](https://eloquentjavascript.net/errata.html) and should be fixed in the 5th reprint.

**Comment by hkiame** [comment]
Awesome
