### ISSUE TITLE
Help understanding a sentence in ch. 10

### ISSUE THREAD

**Issue by B-bit-maker** [marijnh/Eloquent-JavaScript#551]
I'm having difficulties understanding this sentence at page 175:
> You can use JavaScript functions to create local scopes and objects to represent module interfaces.

Which one is the correct way to understand this sentence?
1) You can use JavaScript functions to create local scopes and (you can use) objects to represent module interfaces.
2) You can use JavaScript functions to create (both) local scopes and objects(, in order) to represent module interfaces.

I guess it's the first one, but to be sure I thought I'd ask you.
Thanks (for your answer and for the book).

**Comment by marijnh** [comment]
The first one is indeed the intended interpretation!
