### ISSUE TITLE
Issue with Regexp golf solution

### ISSUE THREAD

**Issue by gpskalra** [marijnh/Eloquent-JavaScript#555]
Regexp Golf is the first exercise of Chapter 9. The issue concerns matching "Any word ending in ious". The solution provided (\ious\b\) will match strings like "$$ious" where non alphanumeric characters precede "ious". Should the right solution be /\b\w*ious\b/ ?

**Comment by gpskalra** [comment]
Similar issue with "word longer than 6 letters". Should it be /\b\w{7,}\b/ instead of /\w{7}/?

**Comment by marijnh** [comment]
I think it's okay to consider 'ious' is itself to be a word ending in 'ious', so I don't feel this is a problem with the solution.
