### ISSUE TITLE
French translation strikes again

### ISSUE THREAD

**Issue by eriam** [marijnh/Eloquent-JavaScript#556]
Hello Marijn,

I started a new translation of your wonderfull book in French. It's at https://github.com/eriam/Eloquent-JavaScript and I completed the first 4 chapters and introduction. I will pause this now as it's appropriate for a beginner level course and get back to it later.

Thanks

Eriam

**Comment by marijnh** [comment]
Great! Let me know if you want help with this, I can ask on Twitter.

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
