### ISSUE TITLE
Suggestion: Chapter 19, Color Input field

### ISSUE THREAD

**Issue by hkiame** [marijnh/Eloquent-JavaScript#557]
The color Input on the controls below the canvas appear to be the odd one out in terms of height. Instead of using a br tag to separator the canvas from the controls we could use a div as a parent to the controls and pass an object as props with a classList property to add some css.

**Comment by marijnh** [comment]
Color input fields look different on different browsers. The code is intentionally minimal and somewhat simplistic in order to keep it digestible for readers—making it look better would be an interesting exercise, but I'm not planning to further complicate the code in the book.
