### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by marcusdavanco** [marijnh/Eloquent-JavaScript#564]
Hello Marijn,

Great book, a previous edition helped me get started into js some time ago, and as you've shared it for free, I'm more than happy to translate it now that I'm reading it a second time.

Here's my fork
https://github.com/MarcusDavanco/Eloquent-JavaScript-PT-BR

Right now there's nothing translated, but I'll work on it it slowly as I review each chapter.

**Comment by marijnh** [comment]
Great to hear! Good luck.

**Comment by MarcusDavanco** [comment]
This will be more difficult than I expected, but here we go...

Introduction translated
https://github.com/MarcusDavanco/Eloquent-JavaScript-PT-BR

**Comment by marijnh** [comment]
Yeah, it's a lot of text, doing a full translation on your own is a big undertaking.

**Comment by joaostein** [comment]
Hey @MarcusDavanco -- the complete 2nd version translation is available [here](https://github.com/braziljs/eloquente-javascript).

For the 3rd version, we have a WIP [here](https://github.com/braziljs/eloquente-javascript/issues/387).

Feel free to join us, if you'd like to contribute.

**Comment by MarcusDavanco** [comment]
![image](https://user-images.githubusercontent.com/4138199/154660760-205fde0f-5ae1-4d9e-bb47-4e40e1703cbd.png)

@joaostein 
Well, fantastic, I'll resume my reading and help you'll finish this.

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.
