### ISSUE TITLE
Apple Books error: error on line 136 at column 15: AttValue: " or ' expected

### ISSUE THREAD

**Issue by dcaaraujo** [marijnh/Eloquent-JavaScript#571]
Hello

I downloaded the epub version of the book and opened it in Apple Books. However, I got the following error:

![IMG_0045](https://github.com/marijnh/Eloquent-JavaScript/assets/78472544/b5104c9c-be17-4b72-b2f2-b4d407055d68)

I cloned the repo and I'll see if I can find the issue. However, it seems the version I compiled using `make book.epub` has errors when I run it though epubcheck.

```
Check finished with errors
Messages: 24 fatals / 332 errors / 10 warnings / 0 infos
```

**Comment by marijnh** [comment]
Oh indeed, can't have unquoted attributes in xhtml. I think attached patch should help.
