### ISSUE TITLE
Potentially incorrect word

### ISSUE THREAD

**Issue by alabhyajindal** [marijnh/Eloquent-JavaScript#574]
Hi Marijn,

Thank you so much for the 4th edition of the book! 

I feel like `Applications` should be replaced by `Functions` at [this](https://github.com/marijnh/Eloquent-JavaScript/blob/ddad254a7d633d1627b4ccfb1dde12b626a4b754/12_language.md?plain=1#L41C7-L41C7) line, resulting in the following.

> Functions are written the way they are in JavaScript, by putting parentheses after an expression and having any number of arguments between those parentheses, separated by commas.

Or maybe I misunderstood the text. Thanks again!

**Comment by marijnh** [comment]
No, 'Applications' is the intended word here—that's how function _applications_ are written, which are a different thing from functions themselves.
