### ISSUE TITLE
Serbian translation

### ISSUE THREAD

**Issue by StefanSlehta** [marijnh/Eloquent-JavaScript#575]
Hi there, started the Serbian translation of the book [on my fork](https://github.com/StefanSlehta/Eloquent-JavaScript), anyone who wants to join in translating or fix my mistakes, you're more than welcome!

Intro, chapters 1,2,3,4 are done now

**Comment by marijnh** [comment]
Nice! Good luck on the rest of the chapters.

**Comment by StefanSlehta** [comment]
Thanks Marijn, even though I'm not a JS developer, this book brought me so much joy reading it when I first found it years ago and taught me many transferrable concepts. 

When I saw it on HackerNews the other day, it brought back a lot of nice memories reading these pages with a morning cup of coffee :)
