### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by ascendho** [marijnh/Eloquent-JavaScript#579]
Hi, I am trying to translate this wonderful book to Chinese, but I found something confusing. The `.md` file is incomplete in some place, I took a screenshot to precisely show what I mean:

![Screenshot 2024-03-20 165610](https://github.com/marijnh/Eloquent-JavaScript/assets/78126591/1ec4f869-9d34-4085-8396-a8ee3a0c1302)

Another thing is that some `.md` files are not consistent with the the content of the book site, maybe give them a update?
Hope you will answer my questions, thanks!

**Comment by ascendho** [comment]
Add: In `00_intro.md` file: 

> Finally, [[Chapter ?](https://github.com/marijnh/Eloquent-JavaScript/issues/fast)](fast) describes some of the considerations that come up when optimizing JavaScript programs for speed.

This paragraph is not on the book site.

**Comment by marijnh** [comment]
The tooling that renders the HTML will fill in the proper chapter numbers for question marks in such internal links. And if you're looking at that paragraph in the Markdown file, surely you noticed that it has an `{{if }}` block around it, which will conditionally output it only in some builds (in this case, the build for the paper book).

**Comment by ascendho** [comment]
Ok, got it!
