### ISSUE TITLE
Grammatical error in the sentence "It’s common to install such libraries is by using NPM"

### ISSUE THREAD

**Issue by hkiame** [marijnh/Eloquent-JavaScript#586]
I found a grammatical error in Chapter 20 titled "Node.js" under the subtitle "Modules." The sentence "It’s common to install such libraries is by using NPM, which we’ll return to in a moment." is incorrect due to the misplaced word "is".

**Steps to Reproduce:**

1. Go to Chapter 20 titled "Node.js".
2. Locate the section/subtitle "Modules".
3. Find the sentence: "It’s common to install such libraries is by using NPM, which we’ll return to in a moment."
4. Notice the grammatical error.

**Suggested Correction:**
The sentence should be corrected to:

- "It’s common to install such libraries using NPM, which we’ll return to in a moment."
or alternatively,
- "The common way to install such libraries is by using NPM, which we’ll return to in a moment."

This change improves the grammatical structure and readability of the sentence.

Pull Request:
I would like to create a pull request to fix this issue.

**Comment by marijnh** [comment]
Fixed in https://github.com/marijnh/Eloquent-JavaScript/pull/587
