### ISSUE TITLE
Unused parse Import in Chapter 20's urlPath Function

### ISSUE THREAD

**Issue by hkiame** [marijnh/Eloquent-JavaScript#588]
### Description

In Chapter 20, under the title "A file server", the code snippet for the `urlPath` function includes the following import statement:

```javascript
import {parse} from "node:url";
```
However, this import is never used within the function or the surrounding code. This may cause confusion for readers and should be removed if it is unnecessary.

### Location
Chapter 20, "A file server" section, in the code snippet for the urlPath function.

### Suggested Fix
Remove the unused import statement:

### Intention to create a Pull Request
 I would like to create a pull request to address this issue by removing the unused import statement.

**Comment by marijnh** [comment]
Thanks for spotting that! Fixed by 39b2738. (Next time, you're welcome to just submit a PR right away—no need to create an issue first.)

**Comment by hkiame** [comment]
Thanks for letting me know.
