### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by backspaces** [marijnh/Eloquent-JavaScript#71]
Why not?  Traceur/Chrome is nearly spec-complete and the TC-39 committee closed the draft.

Sure would draw a crowd, especially since most es6 chat is about just the new stuff, not how it impacts the language as a whole.

**Comment by turtleDev** [comment]
@marijnh ES6 is quite commonplace now. Maybe you'd like to give this another look :)

**Comment by marijnh** [comment]
See https://eloquentjavascript.net/3rd_edition/
