### ISSUE TITLE
Possible bug in chapter4 tableFor()

### ISSUE THREAD

**Issue by almog** [marijnh/Eloquent-JavaScript#97]
I hesitited to open this issue as it seems improbable to me, that such a mistake would stay uncaught but since I think I can reproduce what I suspect is a bug, I'll try to explain:

In the preface to the Phi Correlation implementation, an example for the two-by-two table representation is given:
"For example, the binary number 10 refers to the case where the event (say, "pizza") is true, but Jacques didn’t turn into a squirrel. And since binary 10 is 2 in decimal notation, we will store this value in the array at index 2"

With that said, the binary number 01 should refer to the case when an event is false but the variable is true (Jacques turned into a squirrel).
At any case, as I understand, the tableFor should count the these two cases (pizza+squirrel and not-pizza+squirrel) should not be mapped to the same index.

```
JOURNAL =   [ { "events": ["salad"], "squirrel": true } ];

function hasEvent(event, entry) {
  return entry.events.indexOf(event) != -1;
}

function tableFor(event, journal) {
  var table = [0, 0, 0, 0];
  for (var i = 0; i < journal.length; i++) {
    var entry = journal[i], index = 0;
    if (hasEvent(event, entry)) index += 1;
    if (entry.squirrel) index += 2;
    table[index] += 1;
  }
  return table;
}

console.log(tableFor("pizza", JOURNAL));
// → [0, 0, 1, 0]
// ( rather than [0, 1, 0, 0] )

JOURNAL =   [ { "events": ["salad"], "squirrel": false } ];
console.log(tableFor("salad", JOURNAL));
// → [0, 1, 0, 0]
// rather than [0, 0, 1, 0]
```

If I'm not badly mistaken here, it replaces between (event=true + variable=false) and (event=false + variable=true).

**Comment by kwiat1990** [comment]
I play a litle bit with the code, while reading your book and I've found myself in a situation in which I have just a couple of entries in my Journal. Let's assume I have something like this:

```
addEntry(['work', 'TV', 'spaghetti', 'swimming pool'], false);
addEntry(['work', 'running', 'touched tree'], false);
addEntry(['work', 'weekend', 'peanuts', 'touched tree'], true);
addEntry(['work', 'weekend', 'peanuts'], true);
```
Then using` tableFor` function an `work`  as one of its parameters it returns an array of  `[0, 2, 0, 2]`, which by calculating Phi (using `phi` function) will throw a `NaN`.

**Comment by marijnh** [comment]
That's one property of the phi formula — if you have no examples of one of the values of the variables at all, it can't compute a meaningful value, and will divide by 0.

**Comment by kwiat1990** [comment]
So to make it clear, direct in the `phi` function an adjustment must be made in order to produce a value other than NaN in such a case, which current version of this function doesn't offer?

**Comment by marijnh** [comment]
No, it's not about the _function_, it's about the way the phi coefficient itself is defined (see e.g. [wikipedia](https://en.wikipedia.org/wiki/Phi_coefficient)) — for a table like that, it doesn't produce a meaningful coefficient.
